// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bob.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceBobObjectForEdit = `-- name: AdvanceBobObjectForEdit :execrows
UPDATE bob_objects
SET current_version_id = $1, effective_version_id = NULL,
    next_version_no = next_version_no + 1, revision = revision + 1, updated_at = now(), updated_by = $2
WHERE id = $3 AND entity = $4 AND revision = $5
  AND current_version_id = $6 AND effective_version_id = $6
`

type AdvanceBobObjectForEditParams struct {
	NewVersionID string `db:"new_version_id" json:"new_version_id"`
	ActorID      string `db:"actor_id" json:"actor_id"`
	ID           string `db:"id" json:"id"`
	Entity       string `db:"entity" json:"entity"`
	Revision     int64  `db:"revision" json:"revision"`
	OldVersionID string `db:"old_version_id" json:"old_version_id"`
}

func (q *Queries) AdvanceBobObjectForEdit(ctx context.Context, arg AdvanceBobObjectForEditParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceBobObjectForEdit,
		arg.NewVersionID,
		arg.ActorID,
		arg.ID,
		arg.Entity,
		arg.Revision,
		arg.OldVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const approveBobVersion = `-- name: ApproveBobVersion :execrows
UPDATE bob_versions
SET status = 'EFFECTIVE', revision = revision + 1, reviewed_at = now(), reviewed_by = $1,
    review_comment = $2, updated_at = now(), updated_by = $1
WHERE id = $3 AND object_id = $4 AND entity = $5
  AND revision = $6 AND status = 'PENDING' AND submitted_by <> $1
`

type ApproveBobVersionParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Comment  *string `db:"comment" json:"comment"`
	ID       string  `db:"id" json:"id"`
	ObjectID string  `db:"object_id" json:"object_id"`
	Entity   string  `db:"entity" json:"entity"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) ApproveBobVersion(ctx context.Context, arg ApproveBobVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveBobVersion,
		arg.ActorID,
		arg.Comment,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyBobCustomerDetail = `-- name: CopyBobCustomerDetail :exec
INSERT INTO bob_customer_versions (version_id, name)
SELECT $1, d.name FROM bob_customer_versions d WHERE d.version_id = $2
`

type CopyBobCustomerDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobCustomerDetail(ctx context.Context, arg CopyBobCustomerDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobCustomerDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobEmployeeDetail = `-- name: CopyBobEmployeeDetail :exec
INSERT INTO bob_employee_versions (version_id, name)
SELECT $1, d.name FROM bob_employee_versions d WHERE d.version_id = $2
`

type CopyBobEmployeeDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobEmployeeDetail(ctx context.Context, arg CopyBobEmployeeDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobEmployeeDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobFundAccountDetail = `-- name: CopyBobFundAccountDetail :exec
INSERT INTO bob_fund_account_versions (version_id, name, currency)
SELECT $1, d.name, d.currency FROM bob_fund_account_versions d WHERE d.version_id = $2
`

type CopyBobFundAccountDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobFundAccountDetail(ctx context.Context, arg CopyBobFundAccountDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobFundAccountDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobProductDetail = `-- name: CopyBobProductDetail :exec
INSERT INTO bob_product_versions (version_id, name, unit)
SELECT $1, d.name, d.unit FROM bob_product_versions d WHERE d.version_id = $2
`

type CopyBobProductDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobProductDetail(ctx context.Context, arg CopyBobProductDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobProductDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobServiceDetail = `-- name: CopyBobServiceDetail :exec
INSERT INTO bob_service_versions (version_id, name, unit)
SELECT $1, d.name, d.unit FROM bob_service_versions d WHERE d.version_id = $2
`

type CopyBobServiceDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobServiceDetail(ctx context.Context, arg CopyBobServiceDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobServiceDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobSupplierDetail = `-- name: CopyBobSupplierDetail :exec
INSERT INTO bob_supplier_versions (version_id, name)
SELECT $1, d.name FROM bob_supplier_versions d WHERE d.version_id = $2
`

type CopyBobSupplierDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobSupplierDetail(ctx context.Context, arg CopyBobSupplierDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobSupplierDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const copyBobWarehouseDetail = `-- name: CopyBobWarehouseDetail :exec
INSERT INTO bob_warehouse_versions (version_id, name)
SELECT $1, d.name FROM bob_warehouse_versions d WHERE d.version_id = $2
`

type CopyBobWarehouseDetailParams struct {
	NewVersionID    string `db:"new_version_id" json:"new_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyBobWarehouseDetail(ctx context.Context, arg CopyBobWarehouseDetailParams) error {
	_, err := q.db.Exec(ctx, copyBobWarehouseDetail, arg.NewVersionID, arg.SourceVersionID)
	return err
}

const countBobAuditEvents = `-- name: CountBobAuditEvents :one
SELECT count(*) FROM bob_audit_events WHERE object_id = $1 AND entity = $2
`

type CountBobAuditEventsParams struct {
	ObjectID string `db:"object_id" json:"object_id"`
	Entity   string `db:"entity" json:"entity"`
}

func (q *Queries) CountBobAuditEvents(ctx context.Context, arg CountBobAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBobAuditEvents, arg.ObjectID, arg.Entity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBobObjects = `-- name: CountBobObjects :one
SELECT count(*)
FROM bob_version_views
WHERE entity = $1 AND version_id = current_version_id
  AND (cardinality($2::text[]) = 0 OR status = ANY($2::text[]))
  AND ($3::text = '' OR code ILIKE '%' || $3 || '%' OR name ILIKE '%' || $3 || '%')
`

type CountBobObjectsParams struct {
	Entity   string   `db:"entity" json:"entity"`
	Statuses []string `db:"statuses" json:"statuses"`
	Keyword  string   `db:"keyword" json:"keyword"`
}

func (q *Queries) CountBobObjects(ctx context.Context, arg CountBobObjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBobObjects, arg.Entity, arg.Statuses, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBobVersions = `-- name: CountBobVersions :one
SELECT count(*) FROM bob_versions WHERE object_id = $1 AND entity = $2
`

type CountBobVersionsParams struct {
	ObjectID string `db:"object_id" json:"object_id"`
	Entity   string `db:"entity" json:"entity"`
}

func (q *Queries) CountBobVersions(ctx context.Context, arg CountBobVersionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBobVersions, arg.ObjectID, arg.Entity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBobVersionView = `-- name: GetBobVersionView :one
SELECT object_id, entity, code, current_version_id, effective_version_id, object_revision, object_updated_at, version_id, version_no, status, version_revision, created_at, created_by, updated_at, updated_by, submitted_at, submitted_by, reviewed_at, reviewed_by, review_comment, name, unit, currency FROM bob_version_views
WHERE object_id = $1 AND entity = $2
  AND version_id = COALESCE(NULLIF($3::text, ''), current_version_id)
`

type GetBobVersionViewParams struct {
	ObjectID  string `db:"object_id" json:"object_id"`
	Entity    string `db:"entity" json:"entity"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) GetBobVersionView(ctx context.Context, arg GetBobVersionViewParams) (BobVersionView, error) {
	row := q.db.QueryRow(ctx, getBobVersionView, arg.ObjectID, arg.Entity, arg.VersionID)
	var i BobVersionView
	err := row.Scan(
		&i.ObjectID,
		&i.Entity,
		&i.Code,
		&i.CurrentVersionID,
		&i.EffectiveVersionID,
		&i.ObjectRevision,
		&i.ObjectUpdatedAt,
		&i.VersionID,
		&i.VersionNo,
		&i.Status,
		&i.VersionRevision,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.Name,
		&i.Unit,
		&i.Currency,
	)
	return i, err
}

const insertBobAuditEvent = `-- name: InsertBobAuditEvent :exec
INSERT INTO bob_audit_events (
    id, object_id, version_id, entity, event_type, from_status, to_status, actor_id, comment, request_id, summary
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type InsertBobAuditEventParams struct {
	ID         string  `db:"id" json:"id"`
	ObjectID   string  `db:"object_id" json:"object_id"`
	VersionID  string  `db:"version_id" json:"version_id"`
	Entity     string  `db:"entity" json:"entity"`
	EventType  string  `db:"event_type" json:"event_type"`
	FromStatus *string `db:"from_status" json:"from_status"`
	ToStatus   string  `db:"to_status" json:"to_status"`
	ActorID    string  `db:"actor_id" json:"actor_id"`
	Comment    *string `db:"comment" json:"comment"`
	RequestID  string  `db:"request_id" json:"request_id"`
	Summary    []byte  `db:"summary" json:"summary"`
}

func (q *Queries) InsertBobAuditEvent(ctx context.Context, arg InsertBobAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertBobAuditEvent,
		arg.ID,
		arg.ObjectID,
		arg.VersionID,
		arg.Entity,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Comment,
		arg.RequestID,
		arg.Summary,
	)
	return err
}

const insertBobCustomerDetail = `-- name: InsertBobCustomerDetail :exec
INSERT INTO bob_customer_versions (version_id, name) VALUES ($1, $2)
`

type InsertBobCustomerDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) InsertBobCustomerDetail(ctx context.Context, arg InsertBobCustomerDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobCustomerDetail, arg.VersionID, arg.Name)
	return err
}

const insertBobEmployeeDetail = `-- name: InsertBobEmployeeDetail :exec
INSERT INTO bob_employee_versions (version_id, name) VALUES ($1, $2)
`

type InsertBobEmployeeDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) InsertBobEmployeeDetail(ctx context.Context, arg InsertBobEmployeeDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobEmployeeDetail, arg.VersionID, arg.Name)
	return err
}

const insertBobFundAccountDetail = `-- name: InsertBobFundAccountDetail :exec
INSERT INTO bob_fund_account_versions (version_id, name, currency) VALUES ($1, $2, $3)
`

type InsertBobFundAccountDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
	Currency  string `db:"currency" json:"currency"`
}

func (q *Queries) InsertBobFundAccountDetail(ctx context.Context, arg InsertBobFundAccountDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobFundAccountDetail, arg.VersionID, arg.Name, arg.Currency)
	return err
}

const insertBobObject = `-- name: InsertBobObject :exec
INSERT INTO bob_objects (
    id, entity, code, current_version_id, next_version_no, revision, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, 2, 1, $5, $5
)
`

type InsertBobObjectParams struct {
	ID               string `db:"id" json:"id"`
	Entity           string `db:"entity" json:"entity"`
	Code             string `db:"code" json:"code"`
	CurrentVersionID string `db:"current_version_id" json:"current_version_id"`
	ActorID          string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertBobObject(ctx context.Context, arg InsertBobObjectParams) error {
	_, err := q.db.Exec(ctx, insertBobObject,
		arg.ID,
		arg.Entity,
		arg.Code,
		arg.CurrentVersionID,
		arg.ActorID,
	)
	return err
}

const insertBobProductDetail = `-- name: InsertBobProductDetail :exec
INSERT INTO bob_product_versions (version_id, name, unit) VALUES ($1, $2, $3)
`

type InsertBobProductDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
	Unit      string `db:"unit" json:"unit"`
}

func (q *Queries) InsertBobProductDetail(ctx context.Context, arg InsertBobProductDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobProductDetail, arg.VersionID, arg.Name, arg.Unit)
	return err
}

const insertBobServiceDetail = `-- name: InsertBobServiceDetail :exec
INSERT INTO bob_service_versions (version_id, name, unit) VALUES ($1, $2, $3)
`

type InsertBobServiceDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
	Unit      string `db:"unit" json:"unit"`
}

func (q *Queries) InsertBobServiceDetail(ctx context.Context, arg InsertBobServiceDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobServiceDetail, arg.VersionID, arg.Name, arg.Unit)
	return err
}

const insertBobSupplierDetail = `-- name: InsertBobSupplierDetail :exec
INSERT INTO bob_supplier_versions (version_id, name) VALUES ($1, $2)
`

type InsertBobSupplierDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) InsertBobSupplierDetail(ctx context.Context, arg InsertBobSupplierDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobSupplierDetail, arg.VersionID, arg.Name)
	return err
}

const insertBobVersion = `-- name: InsertBobVersion :exec
INSERT INTO bob_versions (
    id, object_id, entity, version_no, status, revision, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, 'DRAFT', 1, $5, $5
)
`

type InsertBobVersionParams struct {
	ID        string `db:"id" json:"id"`
	ObjectID  string `db:"object_id" json:"object_id"`
	Entity    string `db:"entity" json:"entity"`
	VersionNo int32  `db:"version_no" json:"version_no"`
	ActorID   string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertBobVersion(ctx context.Context, arg InsertBobVersionParams) error {
	_, err := q.db.Exec(ctx, insertBobVersion,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.VersionNo,
		arg.ActorID,
	)
	return err
}

const insertBobWarehouseDetail = `-- name: InsertBobWarehouseDetail :exec
INSERT INTO bob_warehouse_versions (version_id, name) VALUES ($1, $2)
`

type InsertBobWarehouseDetailParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) InsertBobWarehouseDetail(ctx context.Context, arg InsertBobWarehouseDetailParams) error {
	_, err := q.db.Exec(ctx, insertBobWarehouseDetail, arg.VersionID, arg.Name)
	return err
}

const invalidateBobVersion = `-- name: InvalidateBobVersion :execrows
UPDATE bob_versions
SET status = 'INVALID', revision = revision + 1, updated_at = now(), updated_by = $1
WHERE id = $2 AND object_id = $3 AND entity = $4
  AND revision = $5 AND status = 'EFFECTIVE'
`

type InvalidateBobVersionParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	ID       string `db:"id" json:"id"`
	ObjectID string `db:"object_id" json:"object_id"`
	Entity   string `db:"entity" json:"entity"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) InvalidateBobVersion(ctx context.Context, arg InvalidateBobVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateBobVersion,
		arg.ActorID,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBobAuditEvents = `-- name: ListBobAuditEvents :many
SELECT id, object_id, version_id, entity, event_type, from_status, to_status, actor_id,
       occurred_at, comment, request_id, summary
FROM bob_audit_events
WHERE object_id = $1 AND entity = $2
ORDER BY occurred_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListBobAuditEventsParams struct {
	ObjectID   string `db:"object_id" json:"object_id"`
	Entity     string `db:"entity" json:"entity"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageSize   int32  `db:"page_size" json:"page_size"`
}

func (q *Queries) ListBobAuditEvents(ctx context.Context, arg ListBobAuditEventsParams) ([]BobAuditEvent, error) {
	rows, err := q.db.Query(ctx, listBobAuditEvents,
		arg.ObjectID,
		arg.Entity,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BobAuditEvent{}
	for rows.Next() {
		var i BobAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.VersionID,
			&i.Entity,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.OccurredAt,
			&i.Comment,
			&i.RequestID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBobObjects = `-- name: ListBobObjects :many
SELECT object_id, entity, code, current_version_id, effective_version_id, object_revision, object_updated_at, version_id, version_no, status, version_revision, created_at, created_by, updated_at, updated_by, submitted_at, submitted_by, reviewed_at, reviewed_by, review_comment, name, unit, currency
FROM bob_version_views
WHERE entity = $1 AND version_id = current_version_id
  AND (cardinality($2::text[]) = 0 OR status = ANY($2::text[]))
  AND ($3::text = '' OR code ILIKE '%' || $3 || '%' OR name ILIKE '%' || $3 || '%')
ORDER BY
  CASE WHEN $4::text = 'updatedAt' AND $5::text = 'asc' THEN object_updated_at END ASC,
  CASE WHEN $4::text = 'updatedAt' AND $5::text = 'desc' THEN object_updated_at END DESC,
  CASE WHEN $4::text = 'code' AND $5::text = 'asc' THEN code END ASC,
  CASE WHEN $4::text = 'code' AND $5::text = 'desc' THEN code END DESC,
  CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN name END ASC,
  CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN name END DESC,
  CASE WHEN $4::text = 'status' AND $5::text = 'asc' THEN status END ASC,
  CASE WHEN $4::text = 'status' AND $5::text = 'desc' THEN status END DESC,
  CASE WHEN $4::text = 'version' AND $5::text = 'asc' THEN version_no END ASC,
  CASE WHEN $4::text = 'version' AND $5::text = 'desc' THEN version_no END DESC,
  object_id DESC
LIMIT $7 OFFSET $6
`

type ListBobObjectsParams struct {
	Entity     string   `db:"entity" json:"entity"`
	Statuses   []string `db:"statuses" json:"statuses"`
	Keyword    string   `db:"keyword" json:"keyword"`
	SortField  string   `db:"sort_field" json:"sort_field"`
	SortOrder  string   `db:"sort_order" json:"sort_order"`
	PageOffset int32    `db:"page_offset" json:"page_offset"`
	PageSize   int32    `db:"page_size" json:"page_size"`
}

func (q *Queries) ListBobObjects(ctx context.Context, arg ListBobObjectsParams) ([]BobVersionView, error) {
	rows, err := q.db.Query(ctx, listBobObjects,
		arg.Entity,
		arg.Statuses,
		arg.Keyword,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BobVersionView{}
	for rows.Next() {
		var i BobVersionView
		if err := rows.Scan(
			&i.ObjectID,
			&i.Entity,
			&i.Code,
			&i.CurrentVersionID,
			&i.EffectiveVersionID,
			&i.ObjectRevision,
			&i.ObjectUpdatedAt,
			&i.VersionID,
			&i.VersionNo,
			&i.Status,
			&i.VersionRevision,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.Name,
			&i.Unit,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBobVersions = `-- name: ListBobVersions :many
SELECT object_id, entity, code, current_version_id, effective_version_id, object_revision, object_updated_at, version_id, version_no, status, version_revision, created_at, created_by, updated_at, updated_by, submitted_at, submitted_by, reviewed_at, reviewed_by, review_comment, name, unit, currency FROM bob_version_views
WHERE object_id = $1 AND entity = $2
ORDER BY version_no DESC
LIMIT $4 OFFSET $3
`

type ListBobVersionsParams struct {
	ObjectID   string `db:"object_id" json:"object_id"`
	Entity     string `db:"entity" json:"entity"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageSize   int32  `db:"page_size" json:"page_size"`
}

func (q *Queries) ListBobVersions(ctx context.Context, arg ListBobVersionsParams) ([]BobVersionView, error) {
	rows, err := q.db.Query(ctx, listBobVersions,
		arg.ObjectID,
		arg.Entity,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BobVersionView{}
	for rows.Next() {
		var i BobVersionView
		if err := rows.Scan(
			&i.ObjectID,
			&i.Entity,
			&i.Code,
			&i.CurrentVersionID,
			&i.EffectiveVersionID,
			&i.ObjectRevision,
			&i.ObjectUpdatedAt,
			&i.VersionID,
			&i.VersionNo,
			&i.Status,
			&i.VersionRevision,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.Name,
			&i.Unit,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBobObject = `-- name: LockBobObject :one
SELECT id, entity, code, current_version_id, effective_version_id, next_version_no, revision, updated_at
FROM bob_objects
WHERE id = $1 AND entity = $2
FOR UPDATE
`

type LockBobObjectParams struct {
	ID     string `db:"id" json:"id"`
	Entity string `db:"entity" json:"entity"`
}

type LockBobObjectRow struct {
	ID                 string             `db:"id" json:"id"`
	Entity             string             `db:"entity" json:"entity"`
	Code               string             `db:"code" json:"code"`
	CurrentVersionID   string             `db:"current_version_id" json:"current_version_id"`
	EffectiveVersionID *string            `db:"effective_version_id" json:"effective_version_id"`
	NextVersionNo      int32              `db:"next_version_no" json:"next_version_no"`
	Revision           int64              `db:"revision" json:"revision"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockBobObject(ctx context.Context, arg LockBobObjectParams) (LockBobObjectRow, error) {
	row := q.db.QueryRow(ctx, lockBobObject, arg.ID, arg.Entity)
	var i LockBobObjectRow
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.Code,
		&i.CurrentVersionID,
		&i.EffectiveVersionID,
		&i.NextVersionNo,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const lockBobVersion = `-- name: LockBobVersion :one
SELECT id, object_id, entity, version_no, status, revision, submitted_by
FROM bob_versions
WHERE id = $1 AND object_id = $2 AND entity = $3
FOR UPDATE
`

type LockBobVersionParams struct {
	ID       string `db:"id" json:"id"`
	ObjectID string `db:"object_id" json:"object_id"`
	Entity   string `db:"entity" json:"entity"`
}

type LockBobVersionRow struct {
	ID          string  `db:"id" json:"id"`
	ObjectID    string  `db:"object_id" json:"object_id"`
	Entity      string  `db:"entity" json:"entity"`
	VersionNo   int32   `db:"version_no" json:"version_no"`
	Status      string  `db:"status" json:"status"`
	Revision    int64   `db:"revision" json:"revision"`
	SubmittedBy *string `db:"submitted_by" json:"submitted_by"`
}

func (q *Queries) LockBobVersion(ctx context.Context, arg LockBobVersionParams) (LockBobVersionRow, error) {
	row := q.db.QueryRow(ctx, lockBobVersion, arg.ID, arg.ObjectID, arg.Entity)
	var i LockBobVersionRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.Entity,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.SubmittedBy,
	)
	return i, err
}

const markBobVersionSaved = `-- name: MarkBobVersionSaved :execrows
UPDATE bob_versions
SET revision = revision + 1, updated_at = now(), updated_by = $1
WHERE id = $2 AND object_id = $3 AND entity = $4
  AND revision = $5 AND status IN ('DRAFT', 'REJECTED')
`

type MarkBobVersionSavedParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	ID       string `db:"id" json:"id"`
	ObjectID string `db:"object_id" json:"object_id"`
	Entity   string `db:"entity" json:"entity"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) MarkBobVersionSaved(ctx context.Context, arg MarkBobVersionSavedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBobVersionSaved,
		arg.ActorID,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectBobVersion = `-- name: RejectBobVersion :execrows
UPDATE bob_versions
SET status = 'REJECTED', revision = revision + 1, reviewed_at = now(), reviewed_by = $1,
    review_comment = $2, updated_at = now(), updated_by = $1
WHERE id = $3 AND object_id = $4 AND entity = $5
  AND revision = $6 AND status = 'PENDING' AND submitted_by <> $1
`

type RejectBobVersionParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Comment  *string `db:"comment" json:"comment"`
	ID       string  `db:"id" json:"id"`
	ObjectID string  `db:"object_id" json:"object_id"`
	Entity   string  `db:"entity" json:"entity"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) RejectBobVersion(ctx context.Context, arg RejectBobVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectBobVersion,
		arg.ActorID,
		arg.Comment,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveBobEffectiveReference = `-- name: ResolveBobEffectiveReference :one
SELECT o.id AS object_id, o.entity, o.code, v.id AS version_id,
       COALESCE(c.name, s.name, e.name, p.name, sv.name, w.name, f.name) AS name,
       COALESCE(p.unit, sv.unit, '') AS unit, f.currency
FROM bob_objects o
JOIN bob_versions v ON v.object_id = o.id AND v.entity = o.entity
LEFT JOIN bob_customer_versions c ON c.version_id = v.id
LEFT JOIN bob_supplier_versions s ON s.version_id = v.id
LEFT JOIN bob_employee_versions e ON e.version_id = v.id
LEFT JOIN bob_product_versions p ON p.version_id = v.id
LEFT JOIN bob_service_versions sv ON sv.version_id = v.id
LEFT JOIN bob_warehouse_versions w ON w.version_id = v.id
LEFT JOIN bob_fund_account_versions f ON f.version_id = v.id
WHERE o.id = $1 AND o.entity = $2
  AND v.id = $3 AND o.effective_version_id = v.id AND v.status = 'EFFECTIVE'
FOR SHARE OF o
`

type ResolveBobEffectiveReferenceParams struct {
	ObjectID  string `db:"object_id" json:"object_id"`
	Entity    string `db:"entity" json:"entity"`
	VersionID string `db:"version_id" json:"version_id"`
}

type ResolveBobEffectiveReferenceRow struct {
	ObjectID  string  `db:"object_id" json:"object_id"`
	Entity    string  `db:"entity" json:"entity"`
	Code      string  `db:"code" json:"code"`
	VersionID string  `db:"version_id" json:"version_id"`
	Name      string  `db:"name" json:"name"`
	Unit      string  `db:"unit" json:"unit"`
	Currency  *string `db:"currency" json:"currency"`
}

func (q *Queries) ResolveBobEffectiveReference(ctx context.Context, arg ResolveBobEffectiveReferenceParams) (ResolveBobEffectiveReferenceRow, error) {
	row := q.db.QueryRow(ctx, resolveBobEffectiveReference, arg.ObjectID, arg.Entity, arg.VersionID)
	var i ResolveBobEffectiveReferenceRow
	err := row.Scan(
		&i.ObjectID,
		&i.Entity,
		&i.Code,
		&i.VersionID,
		&i.Name,
		&i.Unit,
		&i.Currency,
	)
	return i, err
}

const setBobObjectEffective = `-- name: SetBobObjectEffective :execrows
UPDATE bob_objects
SET effective_version_id = $1, revision = revision + 1, updated_at = now(), updated_by = $2
WHERE id = $3 AND entity = $4 AND current_version_id = $1
  AND effective_version_id IS NULL AND revision = $5
`

type SetBobObjectEffectiveParams struct {
	VersionID *string `db:"version_id" json:"version_id"`
	ActorID   string  `db:"actor_id" json:"actor_id"`
	ID        string  `db:"id" json:"id"`
	Entity    string  `db:"entity" json:"entity"`
	Revision  int64   `db:"revision" json:"revision"`
}

func (q *Queries) SetBobObjectEffective(ctx context.Context, arg SetBobObjectEffectiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBobObjectEffective,
		arg.VersionID,
		arg.ActorID,
		arg.ID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitBobVersion = `-- name: SubmitBobVersion :execrows
UPDATE bob_versions
SET status = 'PENDING', revision = revision + 1, submitted_at = now(), submitted_by = $1,
    reviewed_at = NULL, reviewed_by = NULL, review_comment = NULL, updated_at = now(), updated_by = $1
WHERE id = $2 AND object_id = $3 AND entity = $4
  AND revision = $5 AND status IN ('DRAFT', 'REJECTED')
`

type SubmitBobVersionParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	ID       string  `db:"id" json:"id"`
	ObjectID string  `db:"object_id" json:"object_id"`
	Entity   string  `db:"entity" json:"entity"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) SubmitBobVersion(ctx context.Context, arg SubmitBobVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitBobVersion,
		arg.ActorID,
		arg.ID,
		arg.ObjectID,
		arg.Entity,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchBobObject = `-- name: TouchBobObject :exec
UPDATE bob_objects SET updated_at = now(), updated_by = $1
WHERE id = $2 AND entity = $3
`

type TouchBobObjectParams struct {
	ActorID string `db:"actor_id" json:"actor_id"`
	ID      string `db:"id" json:"id"`
	Entity  string `db:"entity" json:"entity"`
}

func (q *Queries) TouchBobObject(ctx context.Context, arg TouchBobObjectParams) error {
	_, err := q.db.Exec(ctx, touchBobObject, arg.ActorID, arg.ID, arg.Entity)
	return err
}

const updateBobCustomerDetail = `-- name: UpdateBobCustomerDetail :execrows
UPDATE bob_customer_versions SET name = $1 WHERE version_id = $2
`

type UpdateBobCustomerDetailParams struct {
	Name      string `db:"name" json:"name"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobCustomerDetail(ctx context.Context, arg UpdateBobCustomerDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobCustomerDetail, arg.Name, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobEmployeeDetail = `-- name: UpdateBobEmployeeDetail :execrows
UPDATE bob_employee_versions SET name = $1 WHERE version_id = $2
`

type UpdateBobEmployeeDetailParams struct {
	Name      string `db:"name" json:"name"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobEmployeeDetail(ctx context.Context, arg UpdateBobEmployeeDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobEmployeeDetail, arg.Name, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobFundAccountDetail = `-- name: UpdateBobFundAccountDetail :execrows
UPDATE bob_fund_account_versions SET name = $1, currency = $2 WHERE version_id = $3
`

type UpdateBobFundAccountDetailParams struct {
	Name      string `db:"name" json:"name"`
	Currency  string `db:"currency" json:"currency"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobFundAccountDetail(ctx context.Context, arg UpdateBobFundAccountDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobFundAccountDetail, arg.Name, arg.Currency, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobProductDetail = `-- name: UpdateBobProductDetail :execrows
UPDATE bob_product_versions SET name = $1, unit = $2 WHERE version_id = $3
`

type UpdateBobProductDetailParams struct {
	Name      string `db:"name" json:"name"`
	Unit      string `db:"unit" json:"unit"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobProductDetail(ctx context.Context, arg UpdateBobProductDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobProductDetail, arg.Name, arg.Unit, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobServiceDetail = `-- name: UpdateBobServiceDetail :execrows
UPDATE bob_service_versions SET name = $1, unit = $2 WHERE version_id = $3
`

type UpdateBobServiceDetailParams struct {
	Name      string `db:"name" json:"name"`
	Unit      string `db:"unit" json:"unit"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobServiceDetail(ctx context.Context, arg UpdateBobServiceDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobServiceDetail, arg.Name, arg.Unit, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobSupplierDetail = `-- name: UpdateBobSupplierDetail :execrows
UPDATE bob_supplier_versions SET name = $1 WHERE version_id = $2
`

type UpdateBobSupplierDetailParams struct {
	Name      string `db:"name" json:"name"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobSupplierDetail(ctx context.Context, arg UpdateBobSupplierDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobSupplierDetail, arg.Name, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBobWarehouseDetail = `-- name: UpdateBobWarehouseDetail :execrows
UPDATE bob_warehouse_versions SET name = $1 WHERE version_id = $2
`

type UpdateBobWarehouseDetailParams struct {
	Name      string `db:"name" json:"name"`
	VersionID string `db:"version_id" json:"version_id"`
}

func (q *Queries) UpdateBobWarehouseDetail(ctx context.Context, arg UpdateBobWarehouseDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBobWarehouseDetail, arg.Name, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
