// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: led.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateLedControl = `-- name: ActivateLedControl :one
UPDATE led_control
SET status = 'ACTIVE', cutover_date = $1,
    active_generation_id = $2, revision = revision + 1,
    updated_at = now(), updated_by = $3
WHERE singleton = true AND revision = $4
  AND status IN ('DRAFT', 'REOPENING')
RETURNING revision
`

type ActivateLedControlParams struct {
	CutoverDate  pgtype.Date `db:"cutover_date" json:"cutover_date"`
	GenerationID *string     `db:"generation_id" json:"generation_id"`
	ActorID      *string     `db:"actor_id" json:"actor_id"`
	Revision     int64       `db:"revision" json:"revision"`
}

func (q *Queries) ActivateLedControl(ctx context.Context, arg ActivateLedControlParams) (int64, error) {
	row := q.db.QueryRow(ctx, activateLedControl,
		arg.CutoverDate,
		arg.GenerationID,
		arg.ActorID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const archiveActiveLedGeneration = `-- name: ArchiveActiveLedGeneration :exec
UPDATE led_generations SET status = 'ARCHIVED'
WHERE id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ArchiveActiveLedGeneration(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, archiveActiveLedGeneration, generationID)
	return err
}

const cancelLedReopen = `-- name: CancelLedReopen :one
UPDATE led_control AS c
SET status = 'ACTIVE', cutover_date = g.cutover_date, revision = c.revision + 1,
    updated_at = now(), updated_by = $1
FROM led_generations g
WHERE c.singleton = true AND c.status = 'REOPENING'
  AND c.revision = $2 AND g.id = c.active_generation_id
RETURNING c.revision
`

type CancelLedReopenParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) CancelLedReopen(ctx context.Context, arg CancelLedReopenParams) (int64, error) {
	row := q.db.QueryRow(ctx, cancelLedReopen, arg.ActorID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const copyLedOpeningToDraftFund = `-- name: CopyLedOpeningToDraftFund :exec
INSERT INTO led_draft_fund
SELECT id, fund_account_object_id, fund_account_version_id, fund_account_code,
       fund_account_name, currency, amount_cents
FROM led_opening_fund WHERE generation_id = $1
`

func (q *Queries) CopyLedOpeningToDraftFund(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, copyLedOpeningToDraftFund, generationID)
	return err
}

const copyLedOpeningToDraftInventory = `-- name: CopyLedOpeningToDraftInventory :exec
INSERT INTO led_draft_inventory
SELECT id, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
       product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros
FROM led_opening_inventory WHERE generation_id = $1
`

func (q *Queries) CopyLedOpeningToDraftInventory(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, copyLedOpeningToDraftInventory, generationID)
	return err
}

const copyLedOpeningToDraftParty = `-- name: CopyLedOpeningToDraftParty :exec
INSERT INTO led_draft_party
SELECT id, counterparty_entity, counterparty_object_id, counterparty_version_id,
       counterparty_code, counterparty_name, currency, amount_cents
FROM led_opening_party WHERE generation_id = $1
`

func (q *Queries) CopyLedOpeningToDraftParty(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, copyLedOpeningToDraftParty, generationID)
	return err
}

const countLedAuditEvents = `-- name: CountLedAuditEvents :one
SELECT count(*) FROM led_audit_events
`

func (q *Queries) CountLedAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLedAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedFundBalances = `-- name: CountLedFundBalances :one
SELECT count(*) FROM (
    SELECT fund_account_object_id, currency
    FROM led_fund_entries
    WHERE generation_id = $1 AND effective_date <= $2
      AND ($3::text = '' OR fund_account_object_id = $3)
    GROUP BY fund_account_object_id, currency
) balances
`

type CountLedFundBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
}

func (q *Queries) CountLedFundBalances(ctx context.Context, arg CountLedFundBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedFundBalances, arg.GenerationID, arg.AsOfDate, arg.ObjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedFundEntries = `-- name: CountLedFundEntries :one
SELECT count(*) FROM led_fund_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR fund_account_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN amount_delta_cents > 0 THEN 'IN' ELSE 'OUT' END = ANY($7::text[]))
`

type CountLedFundEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
}

func (q *Queries) CountLedFundEntries(ctx context.Context, arg CountLedFundEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedFundEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedInventoryBalances = `-- name: CountLedInventoryBalances :one
SELECT count(*) FROM (
    SELECT warehouse_object_id, product_object_id
    FROM led_inventory_entries
    WHERE generation_id = $1 AND effective_date <= $2
      AND ($3::text = '' OR warehouse_object_id = $3 OR product_object_id = $3)
    GROUP BY warehouse_object_id, product_object_id
) balances
`

type CountLedInventoryBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
}

func (q *Queries) CountLedInventoryBalances(ctx context.Context, arg CountLedInventoryBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedInventoryBalances, arg.GenerationID, arg.AsOfDate, arg.ObjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedInventoryEntries = `-- name: CountLedInventoryEntries :one
SELECT count(*) FROM led_inventory_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR warehouse_object_id = $4 OR product_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN quantity_delta_micros > 0 THEN 'IN' ELSE 'OUT' END = ANY($7::text[]))
`

type CountLedInventoryEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
}

func (q *Queries) CountLedInventoryEntries(ctx context.Context, arg CountLedInventoryEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedInventoryEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedPartyBalances = `-- name: CountLedPartyBalances :one
SELECT count(*) FROM (
    SELECT counterparty_entity, counterparty_object_id, currency
    FROM led_party_entries
    WHERE generation_id = $1 AND effective_date <= $2
      AND ($3::text = '' OR counterparty_object_id = $3)
    GROUP BY counterparty_entity, counterparty_object_id, currency
) balances
`

type CountLedPartyBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
}

func (q *Queries) CountLedPartyBalances(ctx context.Context, arg CountLedPartyBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedPartyBalances, arg.GenerationID, arg.AsOfDate, arg.ObjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedPartyEntries = `-- name: CountLedPartyEntries :one
SELECT count(*) FROM led_party_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR counterparty_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN amount_delta_cents > 0 THEN 'DEBIT' ELSE 'CREDIT' END = ANY($7::text[]))
`

type CountLedPartyEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
}

func (q *Queries) CountLedPartyEntries(ctx context.Context, arg CountLedPartyEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedPartyEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLedDraftFund = `-- name: DeleteLedDraftFund :exec
DELETE FROM led_draft_fund
`

func (q *Queries) DeleteLedDraftFund(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteLedDraftFund)
	return err
}

const deleteLedDraftInventory = `-- name: DeleteLedDraftInventory :exec
DELETE FROM led_draft_inventory
`

func (q *Queries) DeleteLedDraftInventory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteLedDraftInventory)
	return err
}

const deleteLedDraftParty = `-- name: DeleteLedDraftParty :exec
DELETE FROM led_draft_party
`

func (q *Queries) DeleteLedDraftParty(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteLedDraftParty)
	return err
}

const getLedControl = `-- name: GetLedControl :one
SELECT singleton, status, cutover_date, active_generation_id, revision, updated_at, updated_by FROM led_control WHERE singleton = true
`

func (q *Queries) GetLedControl(ctx context.Context) (LedControl, error) {
	row := q.db.QueryRow(ctx, getLedControl)
	var i LedControl
	err := row.Scan(
		&i.Singleton,
		&i.Status,
		&i.CutoverDate,
		&i.ActiveGenerationID,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const hasLedEntriesForSource = `-- name: HasLedEntriesForSource :one
SELECT (
    EXISTS (SELECT 1 FROM led_inventory_entries i WHERE i.generation_id = $1 AND i.source_document_id = $2)
    OR EXISTS (SELECT 1 FROM led_fund_entries f WHERE f.generation_id = $1 AND f.source_document_id = $2)
    OR EXISTS (SELECT 1 FROM led_party_entries p WHERE p.generation_id = $1 AND p.source_document_id = $2)
)::boolean
`

type HasLedEntriesForSourceParams struct {
	TargetGenerationID string `db:"target_generation_id" json:"target_generation_id"`
	TargetDocumentID   string `db:"target_document_id" json:"target_document_id"`
}

func (q *Queries) HasLedEntriesForSource(ctx context.Context, arg HasLedEntriesForSourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLedEntriesForSource, arg.TargetGenerationID, arg.TargetDocumentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasNegativeLedInventoryTimeline = `-- name: HasNegativeLedInventoryTimeline :one
SELECT EXISTS (
    SELECT 1
    FROM (
        SELECT sum(quantity_delta_micros) OVER (
            PARTITION BY warehouse_object_id, product_object_id
            ORDER BY effective_date,
                     CASE WHEN entry_type = 'OPENING' THEN 0 ELSE 1 END,
                     occurred_at, id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS running_quantity
        FROM led_inventory_entries
        WHERE generation_id = $1
    ) timeline
    WHERE running_quantity < 0
)::boolean
`

func (q *Queries) HasNegativeLedInventoryTimeline(ctx context.Context, generationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasNegativeLedInventoryTimeline, generationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLedAuditEvent = `-- name: InsertLedAuditEvent :exec
INSERT INTO led_audit_events (
    id, event_type, from_status, to_status, generation_id, revision,
    actor_id, reason, request_id, summary
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
`

type InsertLedAuditEventParams struct {
	ID           string  `db:"id" json:"id"`
	EventType    string  `db:"event_type" json:"event_type"`
	FromStatus   *string `db:"from_status" json:"from_status"`
	ToStatus     string  `db:"to_status" json:"to_status"`
	GenerationID *string `db:"generation_id" json:"generation_id"`
	Revision     int64   `db:"revision" json:"revision"`
	ActorID      string  `db:"actor_id" json:"actor_id"`
	Reason       *string `db:"reason" json:"reason"`
	RequestID    string  `db:"request_id" json:"request_id"`
	Summary      []byte  `db:"summary" json:"summary"`
}

func (q *Queries) InsertLedAuditEvent(ctx context.Context, arg InsertLedAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertLedAuditEvent,
		arg.ID,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.GenerationID,
		arg.Revision,
		arg.ActorID,
		arg.Reason,
		arg.RequestID,
		arg.Summary,
	)
	return err
}

const insertLedDraftFund = `-- name: InsertLedDraftFund :exec
INSERT INTO led_draft_fund (
    id, fund_account_object_id, fund_account_version_id, fund_account_code,
    fund_account_name, currency, amount_cents
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
`

type InsertLedDraftFundParams struct {
	ID                   string `db:"id" json:"id"`
	FundAccountObjectID  string `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID string `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode      string `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName      string `db:"fund_account_name" json:"fund_account_name"`
	Currency             string `db:"currency" json:"currency"`
	AmountCents          int64  `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) InsertLedDraftFund(ctx context.Context, arg InsertLedDraftFundParams) error {
	_, err := q.db.Exec(ctx, insertLedDraftFund,
		arg.ID,
		arg.FundAccountObjectID,
		arg.FundAccountVersionID,
		arg.FundAccountCode,
		arg.FundAccountName,
		arg.Currency,
		arg.AmountCents,
	)
	return err
}

const insertLedDraftInventory = `-- name: InsertLedDraftInventory :exec
INSERT INTO led_draft_inventory (
    id, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
    product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
`

type InsertLedDraftInventoryParams struct {
	ID                 string `db:"id" json:"id"`
	WarehouseObjectID  string `db:"warehouse_object_id" json:"warehouse_object_id"`
	WarehouseVersionID string `db:"warehouse_version_id" json:"warehouse_version_id"`
	WarehouseCode      string `db:"warehouse_code" json:"warehouse_code"`
	WarehouseName      string `db:"warehouse_name" json:"warehouse_name"`
	ProductObjectID    string `db:"product_object_id" json:"product_object_id"`
	ProductVersionID   string `db:"product_version_id" json:"product_version_id"`
	ProductCode        string `db:"product_code" json:"product_code"`
	ProductName        string `db:"product_name" json:"product_name"`
	ProductUnit        string `db:"product_unit" json:"product_unit"`
	QuantityMicros     int64  `db:"quantity_micros" json:"quantity_micros"`
}

func (q *Queries) InsertLedDraftInventory(ctx context.Context, arg InsertLedDraftInventoryParams) error {
	_, err := q.db.Exec(ctx, insertLedDraftInventory,
		arg.ID,
		arg.WarehouseObjectID,
		arg.WarehouseVersionID,
		arg.WarehouseCode,
		arg.WarehouseName,
		arg.ProductObjectID,
		arg.ProductVersionID,
		arg.ProductCode,
		arg.ProductName,
		arg.ProductUnit,
		arg.QuantityMicros,
	)
	return err
}

const insertLedDraftParty = `-- name: InsertLedDraftParty :exec
INSERT INTO led_draft_party (
    id, counterparty_entity, counterparty_object_id, counterparty_version_id,
    counterparty_code, counterparty_name, currency, amount_cents
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
)
`

type InsertLedDraftPartyParams struct {
	ID                    string `db:"id" json:"id"`
	CounterpartyEntity    string `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  string `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID string `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      string `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      string `db:"counterparty_name" json:"counterparty_name"`
	Currency              string `db:"currency" json:"currency"`
	AmountCents           int64  `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) InsertLedDraftParty(ctx context.Context, arg InsertLedDraftPartyParams) error {
	_, err := q.db.Exec(ctx, insertLedDraftParty,
		arg.ID,
		arg.CounterpartyEntity,
		arg.CounterpartyObjectID,
		arg.CounterpartyVersionID,
		arg.CounterpartyCode,
		arg.CounterpartyName,
		arg.Currency,
		arg.AmountCents,
	)
	return err
}

const insertLedFundEntry = `-- name: InsertLedFundEntry :exec
INSERT INTO led_fund_entries (
    id, generation_id, entry_type, source_entity, source_document_id, source_document_no,
    source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason,
    fund_account_object_id, fund_account_version_id, fund_account_code, fund_account_name,
    currency, amount_delta_cents
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18,
    $19
) ON CONFLICT DO NOTHING
`

type InsertLedFundEntryParams struct {
	ID                   string             `db:"id" json:"id"`
	GenerationID         string             `db:"generation_id" json:"generation_id"`
	EntryType            string             `db:"entry_type" json:"entry_type"`
	SourceEntity         string             `db:"source_entity" json:"source_entity"`
	SourceDocumentID     string             `db:"source_document_id" json:"source_document_id"`
	SourceDocumentNo     string             `db:"source_document_no" json:"source_document_no"`
	SourceLineID         string             `db:"source_line_id" json:"source_line_id"`
	SourceRevision       int64              `db:"source_revision" json:"source_revision"`
	EffectiveDate        pgtype.Date        `db:"effective_date" json:"effective_date"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID              string             `db:"actor_id" json:"actor_id"`
	RequestID            string             `db:"request_id" json:"request_id"`
	Reason               *string            `db:"reason" json:"reason"`
	FundAccountObjectID  string             `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID string             `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode      string             `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName      string             `db:"fund_account_name" json:"fund_account_name"`
	Currency             string             `db:"currency" json:"currency"`
	AmountDeltaCents     int64              `db:"amount_delta_cents" json:"amount_delta_cents"`
}

func (q *Queries) InsertLedFundEntry(ctx context.Context, arg InsertLedFundEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedFundEntry,
		arg.ID,
		arg.GenerationID,
		arg.EntryType,
		arg.SourceEntity,
		arg.SourceDocumentID,
		arg.SourceDocumentNo,
		arg.SourceLineID,
		arg.SourceRevision,
		arg.EffectiveDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
		arg.Reason,
		arg.FundAccountObjectID,
		arg.FundAccountVersionID,
		arg.FundAccountCode,
		arg.FundAccountName,
		arg.Currency,
		arg.AmountDeltaCents,
	)
	return err
}

const insertLedGeneration = `-- name: InsertLedGeneration :exec
INSERT INTO led_generations (id, cutover_date, status, activated_by, request_id)
VALUES ($1, $2, 'ACTIVE', $3, $4)
`

type InsertLedGenerationParams struct {
	ID          string      `db:"id" json:"id"`
	CutoverDate pgtype.Date `db:"cutover_date" json:"cutover_date"`
	ActorID     string      `db:"actor_id" json:"actor_id"`
	RequestID   string      `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertLedGeneration(ctx context.Context, arg InsertLedGenerationParams) error {
	_, err := q.db.Exec(ctx, insertLedGeneration,
		arg.ID,
		arg.CutoverDate,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertLedInventoryEntry = `-- name: InsertLedInventoryEntry :exec
INSERT INTO led_inventory_entries (
    id, generation_id, entry_type, source_entity, source_document_id, source_document_no,
    source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason,
    warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
    product_object_id, product_version_id, product_code, product_name, product_unit,
    quantity_delta_micros
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22,
    $23
) ON CONFLICT DO NOTHING
`

type InsertLedInventoryEntryParams struct {
	ID                  string             `db:"id" json:"id"`
	GenerationID        string             `db:"generation_id" json:"generation_id"`
	EntryType           string             `db:"entry_type" json:"entry_type"`
	SourceEntity        string             `db:"source_entity" json:"source_entity"`
	SourceDocumentID    string             `db:"source_document_id" json:"source_document_id"`
	SourceDocumentNo    string             `db:"source_document_no" json:"source_document_no"`
	SourceLineID        string             `db:"source_line_id" json:"source_line_id"`
	SourceRevision      int64              `db:"source_revision" json:"source_revision"`
	EffectiveDate       pgtype.Date        `db:"effective_date" json:"effective_date"`
	OccurredAt          pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID             string             `db:"actor_id" json:"actor_id"`
	RequestID           string             `db:"request_id" json:"request_id"`
	Reason              *string            `db:"reason" json:"reason"`
	WarehouseObjectID   string             `db:"warehouse_object_id" json:"warehouse_object_id"`
	WarehouseVersionID  string             `db:"warehouse_version_id" json:"warehouse_version_id"`
	WarehouseCode       string             `db:"warehouse_code" json:"warehouse_code"`
	WarehouseName       string             `db:"warehouse_name" json:"warehouse_name"`
	ProductObjectID     string             `db:"product_object_id" json:"product_object_id"`
	ProductVersionID    string             `db:"product_version_id" json:"product_version_id"`
	ProductCode         string             `db:"product_code" json:"product_code"`
	ProductName         string             `db:"product_name" json:"product_name"`
	ProductUnit         string             `db:"product_unit" json:"product_unit"`
	QuantityDeltaMicros int64              `db:"quantity_delta_micros" json:"quantity_delta_micros"`
}

func (q *Queries) InsertLedInventoryEntry(ctx context.Context, arg InsertLedInventoryEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedInventoryEntry,
		arg.ID,
		arg.GenerationID,
		arg.EntryType,
		arg.SourceEntity,
		arg.SourceDocumentID,
		arg.SourceDocumentNo,
		arg.SourceLineID,
		arg.SourceRevision,
		arg.EffectiveDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
		arg.Reason,
		arg.WarehouseObjectID,
		arg.WarehouseVersionID,
		arg.WarehouseCode,
		arg.WarehouseName,
		arg.ProductObjectID,
		arg.ProductVersionID,
		arg.ProductCode,
		arg.ProductName,
		arg.ProductUnit,
		arg.QuantityDeltaMicros,
	)
	return err
}

const insertLedOpeningFundEntries = `-- name: InsertLedOpeningFundEntries :exec
INSERT INTO led_fund_entries (
    id, generation_id, entry_type, source_entity, source_line_id, effective_date,
    occurred_at, actor_id, request_id, fund_account_object_id, fund_account_version_id,
    fund_account_code, fund_account_name, currency, amount_delta_cents
)
SELECT id, $1, 'OPENING', 'opening', id, $2,
       $3, $4, $5,
       fund_account_object_id, fund_account_version_id, fund_account_code,
       fund_account_name, currency, amount_cents
FROM led_draft_fund WHERE amount_cents <> 0
`

type InsertLedOpeningFundEntriesParams struct {
	GenerationID string             `db:"generation_id" json:"generation_id"`
	CutoverDate  pgtype.Date        `db:"cutover_date" json:"cutover_date"`
	OccurredAt   pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	RequestID    string             `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertLedOpeningFundEntries(ctx context.Context, arg InsertLedOpeningFundEntriesParams) error {
	_, err := q.db.Exec(ctx, insertLedOpeningFundEntries,
		arg.GenerationID,
		arg.CutoverDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertLedOpeningFundFromDraft = `-- name: InsertLedOpeningFundFromDraft :exec
INSERT INTO led_opening_fund (
    id, generation_id, fund_account_object_id, fund_account_version_id,
    fund_account_code, fund_account_name, currency, amount_cents
)
SELECT id, $1, fund_account_object_id, fund_account_version_id,
       fund_account_code, fund_account_name, currency, amount_cents
FROM led_draft_fund
`

func (q *Queries) InsertLedOpeningFundFromDraft(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, insertLedOpeningFundFromDraft, generationID)
	return err
}

const insertLedOpeningInventoryEntries = `-- name: InsertLedOpeningInventoryEntries :exec
INSERT INTO led_inventory_entries (
    id, generation_id, entry_type, source_entity, source_line_id, effective_date,
    occurred_at, actor_id, request_id, warehouse_object_id, warehouse_version_id,
    warehouse_code, warehouse_name, product_object_id, product_version_id,
    product_code, product_name, product_unit, quantity_delta_micros
)
SELECT id, $1, 'OPENING', 'opening', id, $2,
       $3, $4, $5,
       warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
       product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros
FROM led_draft_inventory WHERE quantity_micros <> 0
`

type InsertLedOpeningInventoryEntriesParams struct {
	GenerationID string             `db:"generation_id" json:"generation_id"`
	CutoverDate  pgtype.Date        `db:"cutover_date" json:"cutover_date"`
	OccurredAt   pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	RequestID    string             `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertLedOpeningInventoryEntries(ctx context.Context, arg InsertLedOpeningInventoryEntriesParams) error {
	_, err := q.db.Exec(ctx, insertLedOpeningInventoryEntries,
		arg.GenerationID,
		arg.CutoverDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertLedOpeningInventoryFromDraft = `-- name: InsertLedOpeningInventoryFromDraft :exec
INSERT INTO led_opening_inventory (
    id, generation_id, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
    product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros
)
SELECT id, $1, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name,
       product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros
FROM led_draft_inventory
`

func (q *Queries) InsertLedOpeningInventoryFromDraft(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, insertLedOpeningInventoryFromDraft, generationID)
	return err
}

const insertLedOpeningPartyEntries = `-- name: InsertLedOpeningPartyEntries :exec
INSERT INTO led_party_entries (
    id, generation_id, entry_type, source_entity, source_line_id, effective_date,
    occurred_at, actor_id, request_id, counterparty_entity, counterparty_object_id,
    counterparty_version_id, counterparty_code, counterparty_name, currency, amount_delta_cents
)
SELECT id, $1, 'OPENING', 'opening', id, $2,
       $3, $4, $5,
       counterparty_entity, counterparty_object_id, counterparty_version_id,
       counterparty_code, counterparty_name, currency, amount_cents
FROM led_draft_party WHERE amount_cents <> 0
`

type InsertLedOpeningPartyEntriesParams struct {
	GenerationID string             `db:"generation_id" json:"generation_id"`
	CutoverDate  pgtype.Date        `db:"cutover_date" json:"cutover_date"`
	OccurredAt   pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	RequestID    string             `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertLedOpeningPartyEntries(ctx context.Context, arg InsertLedOpeningPartyEntriesParams) error {
	_, err := q.db.Exec(ctx, insertLedOpeningPartyEntries,
		arg.GenerationID,
		arg.CutoverDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertLedOpeningPartyFromDraft = `-- name: InsertLedOpeningPartyFromDraft :exec
INSERT INTO led_opening_party (
    id, generation_id, counterparty_entity, counterparty_object_id, counterparty_version_id,
    counterparty_code, counterparty_name, currency, amount_cents
)
SELECT id, $1, counterparty_entity, counterparty_object_id, counterparty_version_id,
       counterparty_code, counterparty_name, currency, amount_cents
FROM led_draft_party
`

func (q *Queries) InsertLedOpeningPartyFromDraft(ctx context.Context, generationID string) error {
	_, err := q.db.Exec(ctx, insertLedOpeningPartyFromDraft, generationID)
	return err
}

const insertLedPartyEntry = `-- name: InsertLedPartyEntry :exec
INSERT INTO led_party_entries (
    id, generation_id, entry_type, source_entity, source_document_id, source_document_no,
    source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason,
    counterparty_entity, counterparty_object_id, counterparty_version_id,
    counterparty_code, counterparty_name, currency, amount_delta_cents
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17,
    $18, $19, $20
) ON CONFLICT DO NOTHING
`

type InsertLedPartyEntryParams struct {
	ID                    string             `db:"id" json:"id"`
	GenerationID          string             `db:"generation_id" json:"generation_id"`
	EntryType             string             `db:"entry_type" json:"entry_type"`
	SourceEntity          string             `db:"source_entity" json:"source_entity"`
	SourceDocumentID      string             `db:"source_document_id" json:"source_document_id"`
	SourceDocumentNo      string             `db:"source_document_no" json:"source_document_no"`
	SourceLineID          string             `db:"source_line_id" json:"source_line_id"`
	SourceRevision        int64              `db:"source_revision" json:"source_revision"`
	EffectiveDate         pgtype.Date        `db:"effective_date" json:"effective_date"`
	OccurredAt            pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ActorID               string             `db:"actor_id" json:"actor_id"`
	RequestID             string             `db:"request_id" json:"request_id"`
	Reason                *string            `db:"reason" json:"reason"`
	CounterpartyEntity    string             `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  string             `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID string             `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      string             `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      string             `db:"counterparty_name" json:"counterparty_name"`
	Currency              string             `db:"currency" json:"currency"`
	AmountDeltaCents      int64              `db:"amount_delta_cents" json:"amount_delta_cents"`
}

func (q *Queries) InsertLedPartyEntry(ctx context.Context, arg InsertLedPartyEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedPartyEntry,
		arg.ID,
		arg.GenerationID,
		arg.EntryType,
		arg.SourceEntity,
		arg.SourceDocumentID,
		arg.SourceDocumentNo,
		arg.SourceLineID,
		arg.SourceRevision,
		arg.EffectiveDate,
		arg.OccurredAt,
		arg.ActorID,
		arg.RequestID,
		arg.Reason,
		arg.CounterpartyEntity,
		arg.CounterpartyObjectID,
		arg.CounterpartyVersionID,
		arg.CounterpartyCode,
		arg.CounterpartyName,
		arg.Currency,
		arg.AmountDeltaCents,
	)
	return err
}

const listExecutedVouDocumentsForLed = `-- name: ListExecutedVouDocumentsForLed :many
SELECT id, entity, document_no, status, revision, business_date, currency, total_amount_cents, remark, created_at, created_by, updated_at, updated_by, reviewed_at, reviewed_by, approved_at, approved_by, executed_at, executed_by FROM vou_documents WHERE status = 'EXECUTED' ORDER BY executed_at, id
`

func (q *Queries) ListExecutedVouDocumentsForLed(ctx context.Context) ([]VouDocument, error) {
	rows, err := q.db.Query(ctx, listExecutedVouDocumentsForLed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VouDocument{}
	for rows.Next() {
		var i VouDocument
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.DocumentNo,
			&i.Status,
			&i.Revision,
			&i.BusinessDate,
			&i.Currency,
			&i.TotalAmountCents,
			&i.Remark,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.ExecutedAt,
			&i.ExecutedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedAuditEvents = `-- name: ListLedAuditEvents :many
SELECT id, event_type, from_status, to_status, generation_id, revision, actor_id, occurred_at, reason, request_id, summary FROM led_audit_events ORDER BY occurred_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListLedAuditEventsParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageSize   int32 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListLedAuditEvents(ctx context.Context, arg ListLedAuditEventsParams) ([]LedAuditEvent, error) {
	rows, err := q.db.Query(ctx, listLedAuditEvents, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedAuditEvent{}
	for rows.Next() {
		var i LedAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.GenerationID,
			&i.Revision,
			&i.ActorID,
			&i.OccurredAt,
			&i.Reason,
			&i.RequestID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedDraftFund = `-- name: ListLedDraftFund :many
SELECT id, fund_account_object_id, fund_account_version_id, fund_account_code, fund_account_name, currency, amount_cents FROM led_draft_fund ORDER BY fund_account_code, id
`

func (q *Queries) ListLedDraftFund(ctx context.Context) ([]LedDraftFund, error) {
	rows, err := q.db.Query(ctx, listLedDraftFund)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedDraftFund{}
	for rows.Next() {
		var i LedDraftFund
		if err := rows.Scan(
			&i.ID,
			&i.FundAccountObjectID,
			&i.FundAccountVersionID,
			&i.FundAccountCode,
			&i.FundAccountName,
			&i.Currency,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedDraftInventory = `-- name: ListLedDraftInventory :many
SELECT id, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name, product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros FROM led_draft_inventory ORDER BY warehouse_code, product_code, id
`

func (q *Queries) ListLedDraftInventory(ctx context.Context) ([]LedDraftInventory, error) {
	rows, err := q.db.Query(ctx, listLedDraftInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedDraftInventory{}
	for rows.Next() {
		var i LedDraftInventory
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseObjectID,
			&i.WarehouseVersionID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ProductObjectID,
			&i.ProductVersionID,
			&i.ProductCode,
			&i.ProductName,
			&i.ProductUnit,
			&i.QuantityMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedDraftParty = `-- name: ListLedDraftParty :many
SELECT id, counterparty_entity, counterparty_object_id, counterparty_version_id, counterparty_code, counterparty_name, currency, amount_cents FROM led_draft_party ORDER BY counterparty_entity, counterparty_code, currency, id
`

func (q *Queries) ListLedDraftParty(ctx context.Context) ([]LedDraftParty, error) {
	rows, err := q.db.Query(ctx, listLedDraftParty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedDraftParty{}
	for rows.Next() {
		var i LedDraftParty
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyEntity,
			&i.CounterpartyObjectID,
			&i.CounterpartyVersionID,
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.Currency,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedFundBalances = `-- name: ListLedFundBalances :many
SELECT fund_account_object_id,
       (array_agg(fund_account_version_id ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(26) AS fund_account_version_id,
       max(fund_account_code)::varchar(64) AS fund_account_code,
       (array_agg(fund_account_name ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(200) AS fund_account_name,
       currency, sum(amount_delta_cents)::bigint AS balance_cents
FROM led_fund_entries
WHERE generation_id = $1 AND effective_date <= $2
  AND ($3::text = '' OR fund_account_object_id = $3)
GROUP BY fund_account_object_id, currency
ORDER BY max(fund_account_code), currency, fund_account_object_id
LIMIT $5 OFFSET $4
`

type ListLedFundBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

type ListLedFundBalancesRow struct {
	FundAccountObjectID  string `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID string `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode      string `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName      string `db:"fund_account_name" json:"fund_account_name"`
	Currency             string `db:"currency" json:"currency"`
	BalanceCents         int64  `db:"balance_cents" json:"balance_cents"`
}

func (q *Queries) ListLedFundBalances(ctx context.Context, arg ListLedFundBalancesParams) ([]ListLedFundBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLedFundBalances,
		arg.GenerationID,
		arg.AsOfDate,
		arg.ObjectID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedFundBalancesRow{}
	for rows.Next() {
		var i ListLedFundBalancesRow
		if err := rows.Scan(
			&i.FundAccountObjectID,
			&i.FundAccountVersionID,
			&i.FundAccountCode,
			&i.FundAccountName,
			&i.Currency,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedFundEntries = `-- name: ListLedFundEntries :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, fund_account_object_id, fund_account_version_id, fund_account_code, fund_account_name, currency, amount_delta_cents FROM led_fund_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR fund_account_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN amount_delta_cents > 0 THEN 'IN' ELSE 'OUT' END = ANY($7::text[]))
ORDER BY
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'asc' THEN effective_date END ASC,
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'desc' THEN effective_date END DESC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'asc' THEN occurred_at END ASC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'desc' THEN occurred_at END DESC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'asc' THEN source_document_no END ASC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'desc' THEN source_document_no END DESC,
  effective_date DESC, occurred_at DESC, id DESC
LIMIT $11 OFFSET $10
`

type ListLedFundEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
	SortField    string      `db:"sort_field" json:"sort_field"`
	SortOrder    string      `db:"sort_order" json:"sort_order"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListLedFundEntries(ctx context.Context, arg ListLedFundEntriesParams) ([]LedFundEntry, error) {
	rows, err := q.db.Query(ctx, listLedFundEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedFundEntry{}
	for rows.Next() {
		var i LedFundEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.FundAccountObjectID,
			&i.FundAccountVersionID,
			&i.FundAccountCode,
			&i.FundAccountName,
			&i.Currency,
			&i.AmountDeltaCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedFundEntriesBySource = `-- name: ListLedFundEntriesBySource :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, fund_account_object_id, fund_account_version_id, fund_account_code, fund_account_name, currency, amount_delta_cents FROM led_fund_entries
WHERE generation_id = $1
  AND source_document_id = $2
  AND entry_type = 'POSTING'
ORDER BY id
`

type ListLedFundEntriesBySourceParams struct {
	GenerationID     string `db:"generation_id" json:"generation_id"`
	SourceDocumentID string `db:"source_document_id" json:"source_document_id"`
}

func (q *Queries) ListLedFundEntriesBySource(ctx context.Context, arg ListLedFundEntriesBySourceParams) ([]LedFundEntry, error) {
	rows, err := q.db.Query(ctx, listLedFundEntriesBySource, arg.GenerationID, arg.SourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedFundEntry{}
	for rows.Next() {
		var i LedFundEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.FundAccountObjectID,
			&i.FundAccountVersionID,
			&i.FundAccountCode,
			&i.FundAccountName,
			&i.Currency,
			&i.AmountDeltaCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedInventoryBalances = `-- name: ListLedInventoryBalances :many
SELECT warehouse_object_id,
       (array_agg(warehouse_version_id ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(26) AS warehouse_version_id,
       max(warehouse_code)::varchar(64) AS warehouse_code,
       (array_agg(warehouse_name ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(200) AS warehouse_name,
       product_object_id,
       (array_agg(product_version_id ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(26) AS product_version_id,
       max(product_code)::varchar(64) AS product_code,
       (array_agg(product_name ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(200) AS product_name,
       (array_agg(product_unit ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(32) AS product_unit,
       sum(quantity_delta_micros)::bigint AS balance_micros
FROM led_inventory_entries
WHERE generation_id = $1 AND effective_date <= $2
  AND ($3::text = '' OR warehouse_object_id = $3 OR product_object_id = $3)
GROUP BY warehouse_object_id, product_object_id
ORDER BY max(warehouse_code), max(product_code), warehouse_object_id, product_object_id
LIMIT $5 OFFSET $4
`

type ListLedInventoryBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

type ListLedInventoryBalancesRow struct {
	WarehouseObjectID  string `db:"warehouse_object_id" json:"warehouse_object_id"`
	WarehouseVersionID string `db:"warehouse_version_id" json:"warehouse_version_id"`
	WarehouseCode      string `db:"warehouse_code" json:"warehouse_code"`
	WarehouseName      string `db:"warehouse_name" json:"warehouse_name"`
	ProductObjectID    string `db:"product_object_id" json:"product_object_id"`
	ProductVersionID   string `db:"product_version_id" json:"product_version_id"`
	ProductCode        string `db:"product_code" json:"product_code"`
	ProductName        string `db:"product_name" json:"product_name"`
	ProductUnit        string `db:"product_unit" json:"product_unit"`
	BalanceMicros      int64  `db:"balance_micros" json:"balance_micros"`
}

func (q *Queries) ListLedInventoryBalances(ctx context.Context, arg ListLedInventoryBalancesParams) ([]ListLedInventoryBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLedInventoryBalances,
		arg.GenerationID,
		arg.AsOfDate,
		arg.ObjectID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedInventoryBalancesRow{}
	for rows.Next() {
		var i ListLedInventoryBalancesRow
		if err := rows.Scan(
			&i.WarehouseObjectID,
			&i.WarehouseVersionID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ProductObjectID,
			&i.ProductVersionID,
			&i.ProductCode,
			&i.ProductName,
			&i.ProductUnit,
			&i.BalanceMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedInventoryEntries = `-- name: ListLedInventoryEntries :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name, product_object_id, product_version_id, product_code, product_name, product_unit, quantity_delta_micros FROM led_inventory_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR warehouse_object_id = $4 OR product_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN quantity_delta_micros > 0 THEN 'IN' ELSE 'OUT' END = ANY($7::text[]))
ORDER BY
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'asc' THEN effective_date END ASC,
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'desc' THEN effective_date END DESC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'asc' THEN occurred_at END ASC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'desc' THEN occurred_at END DESC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'asc' THEN source_document_no END ASC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'desc' THEN source_document_no END DESC,
  effective_date DESC, occurred_at DESC, id DESC
LIMIT $11 OFFSET $10
`

type ListLedInventoryEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
	SortField    string      `db:"sort_field" json:"sort_field"`
	SortOrder    string      `db:"sort_order" json:"sort_order"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListLedInventoryEntries(ctx context.Context, arg ListLedInventoryEntriesParams) ([]LedInventoryEntry, error) {
	rows, err := q.db.Query(ctx, listLedInventoryEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedInventoryEntry{}
	for rows.Next() {
		var i LedInventoryEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.WarehouseObjectID,
			&i.WarehouseVersionID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ProductObjectID,
			&i.ProductVersionID,
			&i.ProductCode,
			&i.ProductName,
			&i.ProductUnit,
			&i.QuantityDeltaMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedInventoryEntriesBySource = `-- name: ListLedInventoryEntriesBySource :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name, product_object_id, product_version_id, product_code, product_name, product_unit, quantity_delta_micros FROM led_inventory_entries
WHERE generation_id = $1
  AND source_document_id = $2
  AND entry_type = 'POSTING'
ORDER BY id
`

type ListLedInventoryEntriesBySourceParams struct {
	GenerationID     string `db:"generation_id" json:"generation_id"`
	SourceDocumentID string `db:"source_document_id" json:"source_document_id"`
}

func (q *Queries) ListLedInventoryEntriesBySource(ctx context.Context, arg ListLedInventoryEntriesBySourceParams) ([]LedInventoryEntry, error) {
	rows, err := q.db.Query(ctx, listLedInventoryEntriesBySource, arg.GenerationID, arg.SourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedInventoryEntry{}
	for rows.Next() {
		var i LedInventoryEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.WarehouseObjectID,
			&i.WarehouseVersionID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ProductObjectID,
			&i.ProductVersionID,
			&i.ProductCode,
			&i.ProductName,
			&i.ProductUnit,
			&i.QuantityDeltaMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedOpeningFund = `-- name: ListLedOpeningFund :many
SELECT id, generation_id, fund_account_object_id, fund_account_version_id, fund_account_code, fund_account_name, currency, amount_cents FROM led_opening_fund
WHERE generation_id = $1
ORDER BY fund_account_code, id
`

func (q *Queries) ListLedOpeningFund(ctx context.Context, generationID string) ([]LedOpeningFund, error) {
	rows, err := q.db.Query(ctx, listLedOpeningFund, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedOpeningFund{}
	for rows.Next() {
		var i LedOpeningFund
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.FundAccountObjectID,
			&i.FundAccountVersionID,
			&i.FundAccountCode,
			&i.FundAccountName,
			&i.Currency,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedOpeningInventory = `-- name: ListLedOpeningInventory :many
SELECT id, generation_id, warehouse_object_id, warehouse_version_id, warehouse_code, warehouse_name, product_object_id, product_version_id, product_code, product_name, product_unit, quantity_micros FROM led_opening_inventory
WHERE generation_id = $1
ORDER BY warehouse_code, product_code, id
`

func (q *Queries) ListLedOpeningInventory(ctx context.Context, generationID string) ([]LedOpeningInventory, error) {
	rows, err := q.db.Query(ctx, listLedOpeningInventory, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedOpeningInventory{}
	for rows.Next() {
		var i LedOpeningInventory
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.WarehouseObjectID,
			&i.WarehouseVersionID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ProductObjectID,
			&i.ProductVersionID,
			&i.ProductCode,
			&i.ProductName,
			&i.ProductUnit,
			&i.QuantityMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedOpeningParty = `-- name: ListLedOpeningParty :many
SELECT id, generation_id, counterparty_entity, counterparty_object_id, counterparty_version_id, counterparty_code, counterparty_name, currency, amount_cents FROM led_opening_party
WHERE generation_id = $1
ORDER BY counterparty_entity, counterparty_code, currency, id
`

func (q *Queries) ListLedOpeningParty(ctx context.Context, generationID string) ([]LedOpeningParty, error) {
	rows, err := q.db.Query(ctx, listLedOpeningParty, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedOpeningParty{}
	for rows.Next() {
		var i LedOpeningParty
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.CounterpartyEntity,
			&i.CounterpartyObjectID,
			&i.CounterpartyVersionID,
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.Currency,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedPartyBalances = `-- name: ListLedPartyBalances :many
SELECT counterparty_entity, counterparty_object_id,
       (array_agg(counterparty_version_id ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(26) AS counterparty_version_id,
       max(counterparty_code)::varchar(64) AS counterparty_code,
       (array_agg(counterparty_name ORDER BY effective_date DESC, occurred_at DESC, id DESC))[1]::varchar(200) AS counterparty_name,
       currency, sum(amount_delta_cents)::bigint AS balance_cents
FROM led_party_entries
WHERE generation_id = $1 AND effective_date <= $2
  AND ($3::text = '' OR counterparty_object_id = $3)
GROUP BY counterparty_entity, counterparty_object_id, currency
ORDER BY counterparty_entity, max(counterparty_code), currency, counterparty_object_id
LIMIT $5 OFFSET $4
`

type ListLedPartyBalancesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	AsOfDate     pgtype.Date `db:"as_of_date" json:"as_of_date"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

type ListLedPartyBalancesRow struct {
	CounterpartyEntity    string `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  string `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID string `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      string `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      string `db:"counterparty_name" json:"counterparty_name"`
	Currency              string `db:"currency" json:"currency"`
	BalanceCents          int64  `db:"balance_cents" json:"balance_cents"`
}

func (q *Queries) ListLedPartyBalances(ctx context.Context, arg ListLedPartyBalancesParams) ([]ListLedPartyBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLedPartyBalances,
		arg.GenerationID,
		arg.AsOfDate,
		arg.ObjectID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedPartyBalancesRow{}
	for rows.Next() {
		var i ListLedPartyBalancesRow
		if err := rows.Scan(
			&i.CounterpartyEntity,
			&i.CounterpartyObjectID,
			&i.CounterpartyVersionID,
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.Currency,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedPartyEntries = `-- name: ListLedPartyEntries :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, counterparty_entity, counterparty_object_id, counterparty_version_id, counterparty_code, counterparty_name, currency, amount_delta_cents FROM led_party_entries
WHERE generation_id = $1
  AND effective_date >= $2 AND effective_date <= $3
  AND ($4::text = '' OR counterparty_object_id = $4)
  AND ($5::text = '' OR source_entity = $5)
  AND ($6::text = '' OR source_document_no ILIKE '%' || $6 || '%')
  AND (cardinality($7::text[]) = 0
       OR CASE WHEN amount_delta_cents > 0 THEN 'DEBIT' ELSE 'CREDIT' END = ANY($7::text[]))
ORDER BY
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'asc' THEN effective_date END ASC,
  CASE WHEN $8::text = 'effectiveDate' AND $9::text = 'desc' THEN effective_date END DESC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'asc' THEN occurred_at END ASC,
  CASE WHEN $8::text = 'occurredAt' AND $9::text = 'desc' THEN occurred_at END DESC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'asc' THEN source_document_no END ASC,
  CASE WHEN $8::text = 'documentNo' AND $9::text = 'desc' THEN source_document_no END DESC,
  effective_date DESC, occurred_at DESC, id DESC
LIMIT $11 OFFSET $10
`

type ListLedPartyEntriesParams struct {
	GenerationID string      `db:"generation_id" json:"generation_id"`
	DateFrom     pgtype.Date `db:"date_from" json:"date_from"`
	DateTo       pgtype.Date `db:"date_to" json:"date_to"`
	ObjectID     string      `db:"object_id" json:"object_id"`
	SourceEntity string      `db:"source_entity" json:"source_entity"`
	DocumentNo   string      `db:"document_no" json:"document_no"`
	Directions   []string    `db:"directions" json:"directions"`
	SortField    string      `db:"sort_field" json:"sort_field"`
	SortOrder    string      `db:"sort_order" json:"sort_order"`
	PageOffset   int32       `db:"page_offset" json:"page_offset"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListLedPartyEntries(ctx context.Context, arg ListLedPartyEntriesParams) ([]LedPartyEntry, error) {
	rows, err := q.db.Query(ctx, listLedPartyEntries,
		arg.GenerationID,
		arg.DateFrom,
		arg.DateTo,
		arg.ObjectID,
		arg.SourceEntity,
		arg.DocumentNo,
		arg.Directions,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedPartyEntry{}
	for rows.Next() {
		var i LedPartyEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.CounterpartyEntity,
			&i.CounterpartyObjectID,
			&i.CounterpartyVersionID,
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.Currency,
			&i.AmountDeltaCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedPartyEntriesBySource = `-- name: ListLedPartyEntriesBySource :many
SELECT id, generation_id, entry_type, source_entity, source_document_id, source_document_no, source_line_id, source_revision, effective_date, occurred_at, actor_id, request_id, reason, counterparty_entity, counterparty_object_id, counterparty_version_id, counterparty_code, counterparty_name, currency, amount_delta_cents FROM led_party_entries
WHERE generation_id = $1
  AND source_document_id = $2
  AND entry_type = 'POSTING'
ORDER BY id
`

type ListLedPartyEntriesBySourceParams struct {
	GenerationID     string `db:"generation_id" json:"generation_id"`
	SourceDocumentID string `db:"source_document_id" json:"source_document_id"`
}

func (q *Queries) ListLedPartyEntriesBySource(ctx context.Context, arg ListLedPartyEntriesBySourceParams) ([]LedPartyEntry, error) {
	rows, err := q.db.Query(ctx, listLedPartyEntriesBySource, arg.GenerationID, arg.SourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedPartyEntry{}
	for rows.Next() {
		var i LedPartyEntry
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.EntryType,
			&i.SourceEntity,
			&i.SourceDocumentID,
			&i.SourceDocumentNo,
			&i.SourceLineID,
			&i.SourceRevision,
			&i.EffectiveDate,
			&i.OccurredAt,
			&i.ActorID,
			&i.RequestID,
			&i.Reason,
			&i.CounterpartyEntity,
			&i.CounterpartyObjectID,
			&i.CounterpartyVersionID,
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.Currency,
			&i.AmountDeltaCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLedControl = `-- name: LockLedControl :one
SELECT singleton, status, cutover_date, active_generation_id, revision, updated_at, updated_by FROM led_control WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockLedControl(ctx context.Context) (LedControl, error) {
	row := q.db.QueryRow(ctx, lockLedControl)
	var i LedControl
	err := row.Scan(
		&i.Singleton,
		&i.Status,
		&i.CutoverDate,
		&i.ActiveGenerationID,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const reopenLedControl = `-- name: ReopenLedControl :one
UPDATE led_control
SET status = 'REOPENING', revision = revision + 1,
    updated_at = now(), updated_by = $1
WHERE singleton = true AND status = 'ACTIVE' AND revision = $2
RETURNING revision
`

type ReopenLedControlParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) ReopenLedControl(ctx context.Context, arg ReopenLedControlParams) (int64, error) {
	row := q.db.QueryRow(ctx, reopenLedControl, arg.ActorID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const saveLedDraftControl = `-- name: SaveLedDraftControl :one
UPDATE led_control
SET cutover_date = $1, revision = revision + 1,
    updated_at = now(), updated_by = $2
WHERE singleton = true
  AND revision = $3
  AND status IN ('DRAFT', 'REOPENING')
RETURNING revision
`

type SaveLedDraftControlParams struct {
	CutoverDate pgtype.Date `db:"cutover_date" json:"cutover_date"`
	ActorID     *string     `db:"actor_id" json:"actor_id"`
	Revision    int64       `db:"revision" json:"revision"`
}

func (q *Queries) SaveLedDraftControl(ctx context.Context, arg SaveLedDraftControlParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveLedDraftControl, arg.CutoverDate, arg.ActorID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
