// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuditEvent struct {
	ID          string             `db:"id" json:"id"`
	EventType   string             `db:"event_type" json:"event_type"`
	ActorUserID *string            `db:"actor_user_id" json:"actor_user_id"`
	TargetType  *string            `db:"target_type" json:"target_type"`
	TargetID    *string            `db:"target_id" json:"target_id"`
	Result      string             `db:"result" json:"result"`
	RequestID   *string            `db:"request_id" json:"request_id"`
	Summary     []byte             `db:"summary" json:"summary"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
}

type AppPermission struct {
	ID          string             `db:"id" json:"id"`
	Path        string             `db:"path" json:"path"`
	Domain      string             `db:"domain" json:"domain"`
	Entity      string             `db:"entity" json:"entity"`
	Action      string             `db:"action" json:"action"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy   *string            `db:"updated_by" json:"updated_by"`
	Revision    int64              `db:"revision" json:"revision"`
}

type AppRole struct {
	ID          string             `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy   *string            `db:"updated_by" json:"updated_by"`
	Revision    int64              `db:"revision" json:"revision"`
}

type AppRolePermission struct {
	RoleID       string             `db:"role_id" json:"role_id"`
	PermissionID string             `db:"permission_id" json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    *string            `db:"created_by" json:"created_by"`
}

type AppSession struct {
	ID                string             `db:"id" json:"id"`
	UserID            string             `db:"user_id" json:"user_id"`
	TokenHash         []byte             `db:"token_hash" json:"token_hash"`
	CsrfTokenHash     []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt     pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedReason     *string            `db:"revoked_reason" json:"revoked_reason"`
}

type AppUser struct {
	ID                string             `db:"id" json:"id"`
	Username          string             `db:"username" json:"username"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	PasswordHash      string             `db:"password_hash" json:"password_hash"`
	Status            string             `db:"status" json:"status"`
	FailedSigninCount int32              `db:"failed_signin_count" json:"failed_signin_count"`
	LockedUntil       pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         *string            `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy         *string            `db:"updated_by" json:"updated_by"`
	Revision          int64              `db:"revision" json:"revision"`
}

type AppUserRole struct {
	UserID    string             `db:"user_id" json:"user_id"`
	RoleID    string             `db:"role_id" json:"role_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy *string            `db:"created_by" json:"created_by"`
}

type BobAuditEvent struct {
	ID         string             `db:"id" json:"id"`
	ObjectID   string             `db:"object_id" json:"object_id"`
	VersionID  string             `db:"version_id" json:"version_id"`
	Entity     string             `db:"entity" json:"entity"`
	EventType  string             `db:"event_type" json:"event_type"`
	FromStatus *string            `db:"from_status" json:"from_status"`
	ToStatus   string             `db:"to_status" json:"to_status"`
	ActorID    string             `db:"actor_id" json:"actor_id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	Comment    *string            `db:"comment" json:"comment"`
	RequestID  string             `db:"request_id" json:"request_id"`
	Summary    []byte             `db:"summary" json:"summary"`
}

type BobCategoryVersion struct {
	VersionID    string  `db:"version_id" json:"version_id"`
	Entity       string  `db:"entity" json:"entity"`
	Name         string  `db:"name" json:"name"`
	TargetEntity string  `db:"target_entity" json:"target_entity"`
	ParentID     *string `db:"parent_id" json:"parent_id"`
	ParentEntity string  `db:"parent_entity" json:"parent_entity"`
	Description  *string `db:"description" json:"description"`
}

type BobCustomerVersion struct {
	VersionID                 string  `db:"version_id" json:"version_id"`
	Entity                    string  `db:"entity" json:"entity"`
	Name                      string  `db:"name" json:"name"`
	CustomerType              string  `db:"customer_type" json:"customer_type"`
	ShortName                 *string `db:"short_name" json:"short_name"`
	CategoryID                *string `db:"category_id" json:"category_id"`
	CategoryEntity            string  `db:"category_entity" json:"category_entity"`
	TaxNumber                 *string `db:"tax_number" json:"tax_number"`
	ContactName               *string `db:"contact_name" json:"contact_name"`
	ContactPhone              *string `db:"contact_phone" json:"contact_phone"`
	Email                     *string `db:"email" json:"email"`
	Address                   *string `db:"address" json:"address"`
	Remark                    *string `db:"remark" json:"remark"`
	SettlementMethodID        *string `db:"settlement_method_id" json:"settlement_method_id"`
	SettlementMethodEntity    string  `db:"settlement_method_entity" json:"settlement_method_entity"`
	SalespersonEmployeeID     string  `db:"salesperson_employee_id" json:"salesperson_employee_id"`
	SalespersonEmployeeEntity string  `db:"salesperson_employee_entity" json:"salesperson_employee_entity"`
}

type BobDepartmentVersion struct {
	VersionID      string  `db:"version_id" json:"version_id"`
	Entity         string  `db:"entity" json:"entity"`
	Name           string  `db:"name" json:"name"`
	CategoryID     *string `db:"category_id" json:"category_id"`
	CategoryEntity string  `db:"category_entity" json:"category_entity"`
	ParentID       *string `db:"parent_id" json:"parent_id"`
	ParentEntity   string  `db:"parent_entity" json:"parent_entity"`
	Description    *string `db:"description" json:"description"`
}

type BobEmployeeVersion struct {
	VersionID        string      `db:"version_id" json:"version_id"`
	Entity           string      `db:"entity" json:"entity"`
	Name             string      `db:"name" json:"name"`
	CategoryID       *string     `db:"category_id" json:"category_id"`
	CategoryEntity   string      `db:"category_entity" json:"category_entity"`
	DepartmentID     *string     `db:"department_id" json:"department_id"`
	DepartmentEntity string      `db:"department_entity" json:"department_entity"`
	PositionID       *string     `db:"position_id" json:"position_id"`
	PositionEntity   string      `db:"position_entity" json:"position_entity"`
	Phone            *string     `db:"phone" json:"phone"`
	Email            *string     `db:"email" json:"email"`
	HireDate         pgtype.Date `db:"hire_date" json:"hire_date"`
	Remark           *string     `db:"remark" json:"remark"`
}

type BobFundAccountVersion struct {
	VersionID      string  `db:"version_id" json:"version_id"`
	Entity         string  `db:"entity" json:"entity"`
	Name           string  `db:"name" json:"name"`
	Currency       string  `db:"currency" json:"currency"`
	CategoryID     *string `db:"category_id" json:"category_id"`
	CategoryEntity string  `db:"category_entity" json:"category_entity"`
	AccountName    *string `db:"account_name" json:"account_name"`
	BankName       *string `db:"bank_name" json:"bank_name"`
	BankBranch     *string `db:"bank_branch" json:"bank_branch"`
	AccountNumber  *string `db:"account_number" json:"account_number"`
	Remark         *string `db:"remark" json:"remark"`
}

type BobObject struct {
	ID                 string             `db:"id" json:"id"`
	Entity             string             `db:"entity" json:"entity"`
	Code               string             `db:"code" json:"code"`
	CurrentVersionID   string             `db:"current_version_id" json:"current_version_id"`
	EffectiveVersionID *string            `db:"effective_version_id" json:"effective_version_id"`
	NextVersionNo      int32              `db:"next_version_no" json:"next_version_no"`
	Revision           int64              `db:"revision" json:"revision"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy          string             `db:"created_by" json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy          string             `db:"updated_by" json:"updated_by"`
}

type BobPositionVersion struct {
	VersionID      string  `db:"version_id" json:"version_id"`
	Entity         string  `db:"entity" json:"entity"`
	Name           string  `db:"name" json:"name"`
	CategoryID     *string `db:"category_id" json:"category_id"`
	CategoryEntity string  `db:"category_entity" json:"category_entity"`
	Description    *string `db:"description" json:"description"`
}

type BobProductVersion struct {
	VersionID      string  `db:"version_id" json:"version_id"`
	Entity         string  `db:"entity" json:"entity"`
	Name           string  `db:"name" json:"name"`
	Unit           string  `db:"unit" json:"unit"`
	CategoryID     *string `db:"category_id" json:"category_id"`
	CategoryEntity string  `db:"category_entity" json:"category_entity"`
	Specification  *string `db:"specification" json:"specification"`
	Model          *string `db:"model" json:"model"`
	Barcode        *string `db:"barcode" json:"barcode"`
	Remark         *string `db:"remark" json:"remark"`
}

type BobServiceVersion struct {
	VersionID      string  `db:"version_id" json:"version_id"`
	Entity         string  `db:"entity" json:"entity"`
	Name           string  `db:"name" json:"name"`
	Unit           string  `db:"unit" json:"unit"`
	CategoryID     *string `db:"category_id" json:"category_id"`
	CategoryEntity string  `db:"category_entity" json:"category_entity"`
	Description    *string `db:"description" json:"description"`
	Remark         *string `db:"remark" json:"remark"`
}

type BobSettlementMethodVersion struct {
	VersionID   string  `db:"version_id" json:"version_id"`
	Entity      string  `db:"entity" json:"entity"`
	Name        string  `db:"name" json:"name"`
	RuleType    string  `db:"rule_type" json:"rule_type"`
	MonthOffset int32   `db:"month_offset" json:"month_offset"`
	DayOfMonth  *int32  `db:"day_of_month" json:"day_of_month"`
	DayOffset   int32   `db:"day_offset" json:"day_offset"`
	Description *string `db:"description" json:"description"`
}

type BobSupplierVersion struct {
	VersionID                 string  `db:"version_id" json:"version_id"`
	Entity                    string  `db:"entity" json:"entity"`
	Name                      string  `db:"name" json:"name"`
	SupplierType              string  `db:"supplier_type" json:"supplier_type"`
	ShortName                 *string `db:"short_name" json:"short_name"`
	CategoryID                *string `db:"category_id" json:"category_id"`
	CategoryEntity            string  `db:"category_entity" json:"category_entity"`
	TaxNumber                 *string `db:"tax_number" json:"tax_number"`
	ContactName               *string `db:"contact_name" json:"contact_name"`
	ContactPhone              *string `db:"contact_phone" json:"contact_phone"`
	Email                     *string `db:"email" json:"email"`
	Address                   *string `db:"address" json:"address"`
	Remark                    *string `db:"remark" json:"remark"`
	SettlementMethodID        *string `db:"settlement_method_id" json:"settlement_method_id"`
	SettlementMethodEntity    string  `db:"settlement_method_entity" json:"settlement_method_entity"`
	SalespersonEmployeeID     string  `db:"salesperson_employee_id" json:"salesperson_employee_id"`
	SalespersonEmployeeEntity string  `db:"salesperson_employee_entity" json:"salesperson_employee_entity"`
}

type BobVehicleVersion struct {
	VersionID        string         `db:"version_id" json:"version_id"`
	Entity           string         `db:"entity" json:"entity"`
	Name             string         `db:"name" json:"name"`
	PlateNumber      string         `db:"plate_number" json:"plate_number"`
	VehicleType      string         `db:"vehicle_type" json:"vehicle_type"`
	PlatformObjectID string         `db:"platform_object_id" json:"platform_object_id"`
	PlatformEntity   string         `db:"platform_entity" json:"platform_entity"`
	CategoryID       *string        `db:"category_id" json:"category_id"`
	CategoryEntity   string         `db:"category_entity" json:"category_entity"`
	Vin              *string        `db:"vin" json:"vin"`
	EngineNumber     *string        `db:"engine_number" json:"engine_number"`
	LoadCapacityKg   pgtype.Numeric `db:"load_capacity_kg" json:"load_capacity_kg"`
	Remark           *string        `db:"remark" json:"remark"`
}

type BobVersion struct {
	ID            string             `db:"id" json:"id"`
	ObjectID      string             `db:"object_id" json:"object_id"`
	Entity        string             `db:"entity" json:"entity"`
	VersionNo     int32              `db:"version_no" json:"version_no"`
	Status        string             `db:"status" json:"status"`
	Revision      int64              `db:"revision" json:"revision"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy     string             `db:"created_by" json:"created_by"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy     string             `db:"updated_by" json:"updated_by"`
	SubmittedAt   pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	SubmittedBy   *string            `db:"submitted_by" json:"submitted_by"`
	ReviewedAt    pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewedBy    *string            `db:"reviewed_by" json:"reviewed_by"`
	ReviewComment *string            `db:"review_comment" json:"review_comment"`
}

type BobVersionView struct {
	ObjectID                  string             `db:"object_id" json:"object_id"`
	Entity                    string             `db:"entity" json:"entity"`
	Code                      string             `db:"code" json:"code"`
	CurrentVersionID          string             `db:"current_version_id" json:"current_version_id"`
	EffectiveVersionID        *string            `db:"effective_version_id" json:"effective_version_id"`
	ObjectRevision            int64              `db:"object_revision" json:"object_revision"`
	ObjectUpdatedAt           pgtype.Timestamptz `db:"object_updated_at" json:"object_updated_at"`
	VersionID                 string             `db:"version_id" json:"version_id"`
	VersionNo                 int32              `db:"version_no" json:"version_no"`
	Status                    string             `db:"status" json:"status"`
	VersionRevision           int64              `db:"version_revision" json:"version_revision"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy                 string             `db:"created_by" json:"created_by"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy                 string             `db:"updated_by" json:"updated_by"`
	SubmittedAt               pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	SubmittedBy               *string            `db:"submitted_by" json:"submitted_by"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewedBy                *string            `db:"reviewed_by" json:"reviewed_by"`
	ReviewComment             *string            `db:"review_comment" json:"review_comment"`
	Name                      string             `db:"name" json:"name"`
	Unit                      string             `db:"unit" json:"unit"`
	Currency                  *string            `db:"currency" json:"currency"`
	SupplierType              *string            `db:"supplier_type" json:"supplier_type"`
	PlateNumber               *string            `db:"plate_number" json:"plate_number"`
	VehicleType               *string            `db:"vehicle_type" json:"vehicle_type"`
	PlatformObjectID          *string            `db:"platform_object_id" json:"platform_object_id"`
	CustomerType              string             `db:"customer_type" json:"customer_type"`
	ShortName                 string             `db:"short_name" json:"short_name"`
	CategoryID                string             `db:"category_id" json:"category_id"`
	TaxNumber                 string             `db:"tax_number" json:"tax_number"`
	ContactName               string             `db:"contact_name" json:"contact_name"`
	ContactPhone              string             `db:"contact_phone" json:"contact_phone"`
	Email                     string             `db:"email" json:"email"`
	Address                   string             `db:"address" json:"address"`
	Remark                    string             `db:"remark" json:"remark"`
	DepartmentID              string             `db:"department_id" json:"department_id"`
	PositionID                string             `db:"position_id" json:"position_id"`
	Phone                     string             `db:"phone" json:"phone"`
	HireDate                  string             `db:"hire_date" json:"hire_date"`
	Specification             string             `db:"specification" json:"specification"`
	Model                     string             `db:"model" json:"model"`
	Barcode                   string             `db:"barcode" json:"barcode"`
	Description               string             `db:"description" json:"description"`
	ManagerEmployeeID         string             `db:"manager_employee_id" json:"manager_employee_id"`
	Vin                       string             `db:"vin" json:"vin"`
	EngineNumber              string             `db:"engine_number" json:"engine_number"`
	LoadCapacityKg            string             `db:"load_capacity_kg" json:"load_capacity_kg"`
	AccountName               string             `db:"account_name" json:"account_name"`
	BankName                  string             `db:"bank_name" json:"bank_name"`
	BankBranch                string             `db:"bank_branch" json:"bank_branch"`
	AccountNumber             string             `db:"account_number" json:"account_number"`
	TargetEntity              string             `db:"target_entity" json:"target_entity"`
	ParentID                  string             `db:"parent_id" json:"parent_id"`
	SettlementMethodID        string             `db:"settlement_method_id" json:"settlement_method_id"`
	SalespersonEmployeeID     string             `db:"salesperson_employee_id" json:"salesperson_employee_id"`
	SettlementMethodVersionID string             `db:"settlement_method_version_id" json:"settlement_method_version_id"`
	SettlementRuleType        string             `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset     int32              `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth      int32              `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset       int32              `db:"settlement_day_offset" json:"settlement_day_offset"`
}

type BobWarehouseVersion struct {
	VersionID             string  `db:"version_id" json:"version_id"`
	Entity                string  `db:"entity" json:"entity"`
	Name                  string  `db:"name" json:"name"`
	CategoryID            *string `db:"category_id" json:"category_id"`
	CategoryEntity        string  `db:"category_entity" json:"category_entity"`
	Address               *string `db:"address" json:"address"`
	ContactName           *string `db:"contact_name" json:"contact_name"`
	ContactPhone          *string `db:"contact_phone" json:"contact_phone"`
	ManagerEmployeeID     *string `db:"manager_employee_id" json:"manager_employee_id"`
	ManagerEmployeeEntity string  `db:"manager_employee_entity" json:"manager_employee_entity"`
	Remark                *string `db:"remark" json:"remark"`
}

type VouAuditEvent struct {
	ID         string             `db:"id" json:"id"`
	DocumentID string             `db:"document_id" json:"document_id"`
	Entity     string             `db:"entity" json:"entity"`
	EventType  string             `db:"event_type" json:"event_type"`
	FromStatus *string            `db:"from_status" json:"from_status"`
	ToStatus   string             `db:"to_status" json:"to_status"`
	ActorID    string             `db:"actor_id" json:"actor_id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	Reason     *string            `db:"reason" json:"reason"`
	RequestID  string             `db:"request_id" json:"request_id"`
	Summary    []byte             `db:"summary" json:"summary"`
}

type VouDocument struct {
	ID               string             `db:"id" json:"id"`
	Entity           string             `db:"entity" json:"entity"`
	DocumentNo       string             `db:"document_no" json:"document_no"`
	Status           string             `db:"status" json:"status"`
	Revision         int64              `db:"revision" json:"revision"`
	BusinessDate     pgtype.Date        `db:"business_date" json:"business_date"`
	Currency         string             `db:"currency" json:"currency"`
	TotalAmountCents int64              `db:"total_amount_cents" json:"total_amount_cents"`
	Remark           *string            `db:"remark" json:"remark"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy        string             `db:"created_by" json:"created_by"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy        string             `db:"updated_by" json:"updated_by"`
	ReviewedAt       pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewedBy       *string            `db:"reviewed_by" json:"reviewed_by"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ApprovedBy       *string            `db:"approved_by" json:"approved_by"`
	ExecutedAt       pgtype.Timestamptz `db:"executed_at" json:"executed_at"`
	ExecutedBy       *string            `db:"executed_by" json:"executed_by"`
}

type VouDocumentAttachment struct {
	DocumentID string             `db:"document_id" json:"document_id"`
	FileID     string             `db:"file_id" json:"file_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy  string             `db:"created_by" json:"created_by"`
}

type VouDownloadToken struct {
	TokenHash string             `db:"token_hash" json:"token_hash"`
	FileID    string             `db:"file_id" json:"file_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
}

type VouExpenseLine struct {
	ID             string  `db:"id" json:"id"`
	DocumentID     string  `db:"document_id" json:"document_id"`
	DocumentEntity string  `db:"document_entity" json:"document_entity"`
	LineNo         int32   `db:"line_no" json:"line_no"`
	Category       string  `db:"category" json:"category"`
	Description    string  `db:"description" json:"description"`
	AmountCents    int64   `db:"amount_cents" json:"amount_cents"`
	Remark         *string `db:"remark" json:"remark"`
}

type VouExpenseReimbursementDetail struct {
	DocumentID           string `db:"document_id" json:"document_id"`
	Entity               string `db:"entity" json:"entity"`
	EmployeeObjectID     string `db:"employee_object_id" json:"employee_object_id"`
	EmployeeVersionID    string `db:"employee_version_id" json:"employee_version_id"`
	EmployeeCode         string `db:"employee_code" json:"employee_code"`
	EmployeeName         string `db:"employee_name" json:"employee_name"`
	FundAccountObjectID  string `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID string `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode      string `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName      string `db:"fund_account_name" json:"fund_account_name"`
}

type VouFile struct {
	ID              string             `db:"id" json:"id"`
	StorageKey      string             `db:"storage_key" json:"storage_key"`
	OriginalName    string             `db:"original_name" json:"original_name"`
	ContentType     string             `db:"content_type" json:"content_type"`
	DeclaredSize    int64              `db:"declared_size" json:"declared_size"`
	Sha256Hex       string             `db:"sha256_hex" json:"sha256_hex"`
	Status          string             `db:"status" json:"status"`
	UploadTokenHash string             `db:"upload_token_hash" json:"upload_token_hash"`
	UploadExpiresAt pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	StoredAt        pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy       string             `db:"created_by" json:"created_by"`
}

type VouIntermediarySaleOrderDetail struct {
	DocumentID                        string      `db:"document_id" json:"document_id"`
	Entity                            string      `db:"entity" json:"entity"`
	CustomerObjectID                  string      `db:"customer_object_id" json:"customer_object_id"`
	CustomerVersionID                 string      `db:"customer_version_id" json:"customer_version_id"`
	CustomerCode                      string      `db:"customer_code" json:"customer_code"`
	CustomerName                      string      `db:"customer_name" json:"customer_name"`
	SupplierObjectID                  string      `db:"supplier_object_id" json:"supplier_object_id"`
	SupplierVersionID                 string      `db:"supplier_version_id" json:"supplier_version_id"`
	SupplierCode                      string      `db:"supplier_code" json:"supplier_code"`
	SupplierName                      string      `db:"supplier_name" json:"supplier_name"`
	OutboundDate                      pgtype.Date `db:"outbound_date" json:"outbound_date"`
	SignoffDate                       pgtype.Date `db:"signoff_date" json:"signoff_date"`
	PlatformObjectID                  *string     `db:"platform_object_id" json:"platform_object_id"`
	PlatformVersionID                 *string     `db:"platform_version_id" json:"platform_version_id"`
	PlatformCode                      *string     `db:"platform_code" json:"platform_code"`
	PlatformName                      *string     `db:"platform_name" json:"platform_name"`
	VehicleObjectID                   *string     `db:"vehicle_object_id" json:"vehicle_object_id"`
	VehicleVersionID                  *string     `db:"vehicle_version_id" json:"vehicle_version_id"`
	VehicleCode                       *string     `db:"vehicle_code" json:"vehicle_code"`
	VehicleName                       *string     `db:"vehicle_name" json:"vehicle_name"`
	VehiclePlateNumber                *string     `db:"vehicle_plate_number" json:"vehicle_plate_number"`
	DifferenceReason                  *string     `db:"difference_reason" json:"difference_reason"`
	SalespersonObjectID               *string     `db:"salesperson_object_id" json:"salesperson_object_id"`
	SalespersonVersionID              *string     `db:"salesperson_version_id" json:"salesperson_version_id"`
	SalespersonCode                   *string     `db:"salesperson_code" json:"salesperson_code"`
	SalespersonName                   *string     `db:"salesperson_name" json:"salesperson_name"`
	PurchaserObjectID                 *string     `db:"purchaser_object_id" json:"purchaser_object_id"`
	PurchaserVersionID                *string     `db:"purchaser_version_id" json:"purchaser_version_id"`
	PurchaserCode                     *string     `db:"purchaser_code" json:"purchaser_code"`
	PurchaserName                     *string     `db:"purchaser_name" json:"purchaser_name"`
	ContactName                       *string     `db:"contact_name" json:"contact_name"`
	ContactPhone                      *string     `db:"contact_phone" json:"contact_phone"`
	DeliveryAddress                   *string     `db:"delivery_address" json:"delivery_address"`
	CustomerSettlementMethodObjectID  *string     `db:"customer_settlement_method_object_id" json:"customer_settlement_method_object_id"`
	CustomerSettlementMethodVersionID *string     `db:"customer_settlement_method_version_id" json:"customer_settlement_method_version_id"`
	CustomerSettlementMethodCode      *string     `db:"customer_settlement_method_code" json:"customer_settlement_method_code"`
	CustomerSettlementMethodName      *string     `db:"customer_settlement_method_name" json:"customer_settlement_method_name"`
	CustomerSettlementRuleType        *string     `db:"customer_settlement_rule_type" json:"customer_settlement_rule_type"`
	CustomerSettlementMonthOffset     *int32      `db:"customer_settlement_month_offset" json:"customer_settlement_month_offset"`
	CustomerSettlementDayOfMonth      *int32      `db:"customer_settlement_day_of_month" json:"customer_settlement_day_of_month"`
	CustomerSettlementDayOffset       *int32      `db:"customer_settlement_day_offset" json:"customer_settlement_day_offset"`
	CustomerSettlementDescription     *string     `db:"customer_settlement_description" json:"customer_settlement_description"`
	SupplierSettlementMethodObjectID  *string     `db:"supplier_settlement_method_object_id" json:"supplier_settlement_method_object_id"`
	SupplierSettlementMethodVersionID *string     `db:"supplier_settlement_method_version_id" json:"supplier_settlement_method_version_id"`
	SupplierSettlementMethodCode      *string     `db:"supplier_settlement_method_code" json:"supplier_settlement_method_code"`
	SupplierSettlementMethodName      *string     `db:"supplier_settlement_method_name" json:"supplier_settlement_method_name"`
	SupplierSettlementRuleType        *string     `db:"supplier_settlement_rule_type" json:"supplier_settlement_rule_type"`
	SupplierSettlementMonthOffset     *int32      `db:"supplier_settlement_month_offset" json:"supplier_settlement_month_offset"`
	SupplierSettlementDayOfMonth      *int32      `db:"supplier_settlement_day_of_month" json:"supplier_settlement_day_of_month"`
	SupplierSettlementDayOffset       *int32      `db:"supplier_settlement_day_offset" json:"supplier_settlement_day_offset"`
	SupplierSettlementDescription     *string     `db:"supplier_settlement_description" json:"supplier_settlement_description"`
}

type VouNumberCounter struct {
	Entity       string      `db:"entity" json:"entity"`
	BusinessDate pgtype.Date `db:"business_date" json:"business_date"`
	LastValue    int32       `db:"last_value" json:"last_value"`
}

type VouOtherIncomeDetail struct {
	DocumentID            string  `db:"document_id" json:"document_id"`
	Entity                string  `db:"entity" json:"entity"`
	SourceName            string  `db:"source_name" json:"source_name"`
	CounterpartyEntity    *string `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  *string `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID *string `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      *string `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      *string `db:"counterparty_name" json:"counterparty_name"`
	FundAccountObjectID   string  `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID  string  `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode       string  `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName       string  `db:"fund_account_name" json:"fund_account_name"`
	HandlerObjectID       *string `db:"handler_object_id" json:"handler_object_id"`
	HandlerVersionID      *string `db:"handler_version_id" json:"handler_version_id"`
	HandlerCode           *string `db:"handler_code" json:"handler_code"`
	HandlerName           *string `db:"handler_name" json:"handler_name"`
}

type VouPaymentDetail struct {
	DocumentID            string  `db:"document_id" json:"document_id"`
	Entity                string  `db:"entity" json:"entity"`
	CounterpartyEntity    string  `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  string  `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID string  `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      string  `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      string  `db:"counterparty_name" json:"counterparty_name"`
	FundAccountObjectID   string  `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID  string  `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode       string  `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName       string  `db:"fund_account_name" json:"fund_account_name"`
	HandlerObjectID       *string `db:"handler_object_id" json:"handler_object_id"`
	HandlerVersionID      *string `db:"handler_version_id" json:"handler_version_id"`
	HandlerCode           *string `db:"handler_code" json:"handler_code"`
	HandlerName           *string `db:"handler_name" json:"handler_name"`
}

type VouProductLine struct {
	ID                string  `db:"id" json:"id"`
	DocumentID        string  `db:"document_id" json:"document_id"`
	DocumentEntity    string  `db:"document_entity" json:"document_entity"`
	LineNo            int32   `db:"line_no" json:"line_no"`
	ProductObjectID   string  `db:"product_object_id" json:"product_object_id"`
	ProductVersionID  string  `db:"product_version_id" json:"product_version_id"`
	ProductCode       string  `db:"product_code" json:"product_code"`
	ProductName       string  `db:"product_name" json:"product_name"`
	ProductUnit       string  `db:"product_unit" json:"product_unit"`
	OrderedQtyMicros  int64   `db:"ordered_qty_micros" json:"ordered_qty_micros"`
	UnitPriceCents    int64   `db:"unit_price_cents" json:"unit_price_cents"`
	LineAmountCents   int64   `db:"line_amount_cents" json:"line_amount_cents"`
	OutboundQtyMicros *int64  `db:"outbound_qty_micros" json:"outbound_qty_micros"`
	SignedQtyMicros   *int64  `db:"signed_qty_micros" json:"signed_qty_micros"`
	RejectedQtyMicros *int64  `db:"rejected_qty_micros" json:"rejected_qty_micros"`
	LossQtyMicros     *int64  `db:"loss_qty_micros" json:"loss_qty_micros"`
	InboundQtyMicros  *int64  `db:"inbound_qty_micros" json:"inbound_qty_micros"`
	Remark            *string `db:"remark" json:"remark"`
}

type VouPurchaseOrderDetail struct {
	DocumentID                string      `db:"document_id" json:"document_id"`
	Entity                    string      `db:"entity" json:"entity"`
	SupplierObjectID          string      `db:"supplier_object_id" json:"supplier_object_id"`
	SupplierVersionID         string      `db:"supplier_version_id" json:"supplier_version_id"`
	SupplierCode              string      `db:"supplier_code" json:"supplier_code"`
	SupplierName              string      `db:"supplier_name" json:"supplier_name"`
	InboundDate               pgtype.Date `db:"inbound_date" json:"inbound_date"`
	DifferenceReason          *string     `db:"difference_reason" json:"difference_reason"`
	PurchaserObjectID         *string     `db:"purchaser_object_id" json:"purchaser_object_id"`
	PurchaserVersionID        *string     `db:"purchaser_version_id" json:"purchaser_version_id"`
	PurchaserCode             *string     `db:"purchaser_code" json:"purchaser_code"`
	PurchaserName             *string     `db:"purchaser_name" json:"purchaser_name"`
	WarehouseObjectID         *string     `db:"warehouse_object_id" json:"warehouse_object_id"`
	WarehouseVersionID        *string     `db:"warehouse_version_id" json:"warehouse_version_id"`
	WarehouseCode             *string     `db:"warehouse_code" json:"warehouse_code"`
	WarehouseName             *string     `db:"warehouse_name" json:"warehouse_name"`
	ContactName               *string     `db:"contact_name" json:"contact_name"`
	ContactPhone              *string     `db:"contact_phone" json:"contact_phone"`
	SettlementMethodObjectID  *string     `db:"settlement_method_object_id" json:"settlement_method_object_id"`
	SettlementMethodVersionID *string     `db:"settlement_method_version_id" json:"settlement_method_version_id"`
	SettlementMethodCode      *string     `db:"settlement_method_code" json:"settlement_method_code"`
	SettlementMethodName      *string     `db:"settlement_method_name" json:"settlement_method_name"`
	SettlementRuleType        *string     `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset     *int32      `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth      *int32      `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset       *int32      `db:"settlement_day_offset" json:"settlement_day_offset"`
	SettlementDescription     *string     `db:"settlement_description" json:"settlement_description"`
}

type VouReceiptDetail struct {
	DocumentID            string  `db:"document_id" json:"document_id"`
	Entity                string  `db:"entity" json:"entity"`
	CounterpartyEntity    string  `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID  string  `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyVersionID string  `db:"counterparty_version_id" json:"counterparty_version_id"`
	CounterpartyCode      string  `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName      string  `db:"counterparty_name" json:"counterparty_name"`
	FundAccountObjectID   string  `db:"fund_account_object_id" json:"fund_account_object_id"`
	FundAccountVersionID  string  `db:"fund_account_version_id" json:"fund_account_version_id"`
	FundAccountCode       string  `db:"fund_account_code" json:"fund_account_code"`
	FundAccountName       string  `db:"fund_account_name" json:"fund_account_name"`
	HandlerObjectID       *string `db:"handler_object_id" json:"handler_object_id"`
	HandlerVersionID      *string `db:"handler_version_id" json:"handler_version_id"`
	HandlerCode           *string `db:"handler_code" json:"handler_code"`
	HandlerName           *string `db:"handler_name" json:"handler_name"`
}

type VouSaleOrderDetail struct {
	DocumentID                string      `db:"document_id" json:"document_id"`
	Entity                    string      `db:"entity" json:"entity"`
	CustomerObjectID          string      `db:"customer_object_id" json:"customer_object_id"`
	CustomerVersionID         string      `db:"customer_version_id" json:"customer_version_id"`
	CustomerCode              string      `db:"customer_code" json:"customer_code"`
	CustomerName              string      `db:"customer_name" json:"customer_name"`
	OutboundDate              pgtype.Date `db:"outbound_date" json:"outbound_date"`
	SignoffDate               pgtype.Date `db:"signoff_date" json:"signoff_date"`
	PlatformObjectID          *string     `db:"platform_object_id" json:"platform_object_id"`
	PlatformVersionID         *string     `db:"platform_version_id" json:"platform_version_id"`
	PlatformCode              *string     `db:"platform_code" json:"platform_code"`
	PlatformName              *string     `db:"platform_name" json:"platform_name"`
	VehicleObjectID           *string     `db:"vehicle_object_id" json:"vehicle_object_id"`
	VehicleVersionID          *string     `db:"vehicle_version_id" json:"vehicle_version_id"`
	VehicleCode               *string     `db:"vehicle_code" json:"vehicle_code"`
	VehicleName               *string     `db:"vehicle_name" json:"vehicle_name"`
	VehiclePlateNumber        *string     `db:"vehicle_plate_number" json:"vehicle_plate_number"`
	DifferenceReason          *string     `db:"difference_reason" json:"difference_reason"`
	SalespersonObjectID       *string     `db:"salesperson_object_id" json:"salesperson_object_id"`
	SalespersonVersionID      *string     `db:"salesperson_version_id" json:"salesperson_version_id"`
	SalespersonCode           *string     `db:"salesperson_code" json:"salesperson_code"`
	SalespersonName           *string     `db:"salesperson_name" json:"salesperson_name"`
	WarehouseObjectID         *string     `db:"warehouse_object_id" json:"warehouse_object_id"`
	WarehouseVersionID        *string     `db:"warehouse_version_id" json:"warehouse_version_id"`
	WarehouseCode             *string     `db:"warehouse_code" json:"warehouse_code"`
	WarehouseName             *string     `db:"warehouse_name" json:"warehouse_name"`
	ContactName               *string     `db:"contact_name" json:"contact_name"`
	ContactPhone              *string     `db:"contact_phone" json:"contact_phone"`
	DeliveryAddress           *string     `db:"delivery_address" json:"delivery_address"`
	SettlementMethodObjectID  *string     `db:"settlement_method_object_id" json:"settlement_method_object_id"`
	SettlementMethodVersionID *string     `db:"settlement_method_version_id" json:"settlement_method_version_id"`
	SettlementMethodCode      *string     `db:"settlement_method_code" json:"settlement_method_code"`
	SettlementMethodName      *string     `db:"settlement_method_name" json:"settlement_method_name"`
	SettlementRuleType        *string     `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset     *int32      `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth      *int32      `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset       *int32      `db:"settlement_day_offset" json:"settlement_day_offset"`
	SettlementDescription     *string     `db:"settlement_description" json:"settlement_description"`
}
